SELECT DISTINCT
ASD.CONTRACT_ID AS DOGOVOR -- Íîìåð êðåäèòíîãî äîãîâîðà	
,ASD.ISSUE_DT AS DTV -- Äàòà âûäà÷è
,CASE	WHEN EXTRACT(MONTH FROM ASD.issue_dt) <10 THEN TRIM ( LEADING ' ' FROM EXTRACT(YEAR FROM ASD.issue_dt)) || '_0' || TRIM (LEADING ' ' FROM EXTRACT(MONTH FROM ASD.issue_dt))
			ELSE  TRIM ( LEADING ' ' FROM EXTRACT(YEAR FROM ASD.issue_dt)) || '_' || TRIM (LEADING ' ' FROM EXTRACT(MONTH FROM ASD.issue_dt)) 
END AS DTYM -- Ïîêîëåíèå âûäà÷è
,CASE WHEN ASD.PRODUCT_OPERATIONAL_ID IN  ('À1','À2','À5') THEN 'ÀÝ' ELSE ASD.PRODUCT_OPERATIONAL_ID END PRODUCT --	Ïðîäóêò
,CASE
			WHEN (UPPER(PSH.product_sub_nm) LIKE '%LIFAN FINANCE%' AND ASD.product_operational_id = 'ÀË') THEN 'Lifan (6.9%)'
			WHEN (UPPER(PSH.product_sub_nm) LIKE '%FORCE%' AND ASD.product_operational_id = 'ÀË') THEN 'Lifan (7.34%)'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%KICK DOWN LOCAL%' THEN 'Kick down local'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%KICK DOWN PLUS%' THEN 'Kick down Plus'
			WHEN (UPPER(PSH.product_sub_nm) LIKE '%KICK%' AND ASD.product_operational_id NOT IN ('ÀÁ')) THEN 'Kick down' /*AND X.BRAND_NM NOT IN ('Ford'*/
			/*WHEN (upper(PSH.product_sub_nm) LIKE '%KICK%' AND ASD.product_operational_id NOT IN ('ÀÁ') AND ASD.BRAND_NM = 'Ford') THEN 'Ford Kick down'*/
			WHEN UPPER(PSH.product_sub_nm) LIKE '%Ú%' THEN 'ÝêñïðåññÚ'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%ÌÈËËÈÎÍ%' THEN 'Ìèëëèîí'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%ÏÐÈÂÈËÅÃÈß%' THEN 'ÀâòîÏðèâèëåãèÿ'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%FINANCIAL SERVICES DIRECT%' THEN 'ÏÐÑ Land_Jaguar'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%VOLVO DIRECT%' THEN 'ÏÐÑ Volvo'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%ÄÐÀÉÂÅÐ%' THEN 'Äðàéâåð'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%ÀÂÒÎÊÎÐÏÎÐÀÖÈß%' THEN 'ÀâòîÊîðïîðàöèÿ'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%ÔÈÇ%' THEN 'C2C'
			WHEN (UPPER(PSH.product_sub_nm) LIKE '%LADA FINANCE SPECIAL%' AND PSH.product_sub_nm LIKE '%02.11.2016%' AND ASD.brand_nm IN ('Lada') AND ASD.product_operational_id NOT IN ('ÀÁ')) THEN 'Lada Finance Special'
            WHEN (UPPER(PSH.product_sub_nm) LIKE '%LADA FINANCE SPECIAL%' AND PSH.product_sub_nm LIKE '%02.02.2017%' AND ASD.brand_nm IN ('Lada') AND ASD.product_operational_id NOT IN ('ÀÁ')) THEN 'Lada Finance Special'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%Ñ ÏÎÍÈÆÀÞÙÈÌ!%' THEN 'Ñ ïîíèæàþùèì!'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%BLACKAUTOFRIDAY%' THEN 'BlackAutoFriday'
			WHEN UPPER(ASD.PRODUCT_SUB_NM) LIKE '%ÄÀÉ ÏßÒÜ!%' THEN 'Äàé ïÿòü!'
			WHEN UPPER(PSH.PRODUCT_SUB_NM) LIKE '%ÀÂÒÎËÀÉÒ ÏÐÎÌÎ%'  AND ASD.OWNER_TYPE_CD = 'Ñòàðûé' THEN 'Àâòîïðîáåã'
			ELSE 'Ïðî÷åå'
END AS PROGRAMMA -- Ðàñêðàñêà Ïðîãðàììû
,CASE 
	WHEN CIOD.extra_office_id IN ('0019', '0119', '0219', '1019', '1219', '1119', '1319', '1419', '1519', '1719') THEN 'Òîëüÿòòè' 
	WHEN CIOD.extra_office_id IN ('1015', '1815', '2915', '1115') THEN 'Òþìåíü' 
	WHEN CIOD.extra_office_id IN ('4215', '2315', '1415', '3015', '2715') THEN 'Ñóðãóò'
	WHEN CIOD.extra_office_id IN ('2464') THEN 'Óôà'	
ELSE SPR.mak_nm 
END AS MAK -- Ãîðîäà ÌÀÊ
,ASD.OWNER_TYPE_CD AS New_Old -- Íîâûé à/ì èëè ÀÑÏ
,ASD.LOAN_RUR_AMT --- Ñóììà âûäà÷è â ðóáëÿõ
,ASD.AUTO_HOLDING_LVL_1_CD AS HOLDING
,CASE WHEN ASD.brand_nm = 'Chevrolet' AND ASD.model_nm = 'Niva' THEN 'Chevrolet Niva' ELSE ASD.brand_nm END AS Marka
,CASE 
	 WHEN Marka = 'Chevrolet Niva' THEN 'ÔÏ'
	 WHEN Marka = 'Hyundai' THEN 'ÔÏ'
	 WHEN Marka = 'Jaguar' THEN 'ÔÏ'
	 WHEN Marka = 'Kia' THEN 'ÔÏ'
	 WHEN Marka = 'Lada' THEN 'ÔÏ'
	 WHEN Marka = 'Land Rover' THEN 'ÔÏ'
	 WHEN Marka = 'Lifan' THEN 'ÔÏ'
	 WHEN Marka = 'Subaru' THEN 'ÔÏ'
	 WHEN Marka = 'Suzuki' THEN 'ÔÏ'
	 WHEN Marka = 'UAZ' THEN 'ÔÏ'
	 WHEN Marka = 'Volvo' THEN 'ÔÏ'
	 WHEN Marka = 'ÃÀÇ' THEN 'ÔÏ'
	 ELSE 'íåÔÏ'
END AS FP_notFP -- Ìàðêà à/ì ÔÏ èëè íåÔÏ
,CASE 
	WHEN DV.vehicle_manufacturer_residence = 'RUS' THEN 'Îòå÷åñòâåííàÿ'
	WHEN DV.vehicle_manufacturer_residence = 'NORUS' THEN 'Èíîìàðêà'
	ELSE 'Íåò èíôîðìàöèè' 
END AS RUS_NO
-----SU sector
,1 AS KRED -- Êðåäèòû ñ÷åò÷èê
,CASE 
	WHEN ASD.COMPREH_COVER_INSURANT_NM LIKE '%ÂÒÁ%' AND ASD.COMPREH_COVER_CONTRACT_ID LIKE '%À342%' THEN 1 --êèðèëëèöà
	WHEN ASD.COMPREH_COVER_INSURANT_NM LIKE '%ÂÒÁ%' AND ASD.COMPREH_COVER_CONTRACT_ID LIKE '%A342%' THEN 1 --ëàòèíèöà
	ELSE 0 
END AS VKASKO_VTB -- ÂìåñòîÊàñêî ÂÒÁ-Ñ
,CASE 
	WHEN ASD.COMPREH_COVER_INSURANT_NM LIKE '%ÂÒÁ%' AND ASD.COMPREH_COVER_CONTRACT_ID LIKE '%A302%' THEN 1 --ëàòèíèöà
	WHEN ASD.COMPREH_COVER_INSURANT_NM LIKE '%ÂÒÁ%' AND ASD.COMPREH_COVER_CONTRACT_ID LIKE '%À302%' THEN 1 --êèðèëëèöà
	WHEN ASD.COMPREH_COVER_INSURANT_NM LIKE '%ÂÒÁ%' AND ASD.COMPREH_COVER_CONTRACT_ID LIKE '%A301%' THEN 1 --ëàòèíèöà
	WHEN ASD.COMPREH_COVER_INSURANT_NM LIKE '%ÂÒÁ%' AND ASD.COMPREH_COVER_CONTRACT_ID LIKE '%À301%' THEN 1 --êèðèëëèöà
	ELSE 0 
END AS MINIK -- ÌèíèÊÀÑÊÎ ÂÒÁ-Ñ
,CASE WHEN ASD.life_insurance_insurant_nm IS NOT NULL THEN
	CASE WHEN UPPER (ASD.life_insurance_contract_id) LIKE '%K%' 
		OR UPPER (ASD.life_insurance_contract_id) LIKE '%Ê%'
		OR UPPER (ASD.life_insurance_contract_id) LIKE '%A%'
		OR UPPER (ASD.life_insurance_contract_id) LIKE '%À%'
		OR UPPER (ASD.life_insurance_insurant_nm) LIKE '%ÂÒÁ%' THEN 1 ELSE 0 
	END ELSE 0 
END AS SJVTB -- ÑÆ ÂÒÁ
,CASE
	WHEN UPPER (AIHDK2.INSURANCE_COMPANY_ID) LIKE '%ÂÒÁ%' THEN 1	--new logic
	WHEN UPPER (AIHDK2.INSURANCE_CONTRACT_ID) LIKE '%K%' THEN 1		--new logic	
	WHEN UPPER (AIHDK2.INSURANCE_CONTRACT_ID) LIKE '%Ê%' THEN 1		--new logic
	WHEN UPPER (AIHDK2.INSURANCE_CONTRACT_ID) LIKE '%A%' THEN 1		--new logic
	WHEN UPPER (AIHDK2.INSURANCE_CONTRACT_ID) LIKE '%À%' THEN 1		--new logic
	ELSE 0 
END AS DKVTB  -------ÄÊÀÑÊÎ ÂÒÁ 
------Rastorjenia SU VTB
,CASE WHEN CPVK.CONTRACT_ID IS NOT NULL THEN 1 ELSE 0 END AS FLG_VK_RASTOR
,CASE WHEN CPMK.CONTRACT_ID IS NOT NULL THEN 1 ELSE 0 END AS FLG_MK_RASTOR
,CASE WHEN CPSJ.CONTRACT_ID IS NOT NULL THEN 1 ELSE 0 END AS FLG_SJ_RASTOR
,CASE WHEN CPDK.CONTRACT_ID IS NOT NULL THEN 1 ELSE 0 END AS FLG_DK_RASTOR
----Premii
,CASE WHEN ASD.COMPREH_COVER_INSURANT_NM LIKE '%ÂÒÁ%' THEN ASD.COMPREH_COVER_PAYMENT_AMT ELSE NULL 
END AS Ñòðàõ_ïðåìèÿ_ÂìåñòîÊÀÑÊÎ_ÂÒÁ
,CASE WHEN ASD.COMPREH_COVER_INSURANT_NM LIKE '%ÂÒÁ%' AND ASD.COMPREH_COVER_PAYMENT_DESC LIKE '%çà ñ÷åò%' THEN ASD.COMPREH_COVER_PAYMENT_AMT ELSE NULL 
END AS Ñòðàõ_ïðåìèÿ_ÌèíèÊÀÑÊÎ_ÂÒÁ
,CASE WHEN ASD.LIFE_INSURANCE_INSURANT_NM LIKE '%ÂÒÁ%' THEN ASD.LIFE_INSURANCE_PAYMENT_AMT ELSE NULL 
END AS Ñòðàõ_ïðåìèÿ_ÑÆ_ÂÒÁ
,CASE 
	WHEN UPPER (AIHDK2.INSURANCE_COMPANY_ID) LIKE '%ÂÒÁ%' THEN CAST(RIHDK2.PAYMENT_AMT AS DECIMAL(23,2))
	WHEN UPPER (AIHDK2.INSURANCE_CONTRACT_ID) LIKE '%K%' THEN CAST(RIHDK2.PAYMENT_AMT AS DECIMAL(23,2))
	WHEN UPPER (AIHDK2.INSURANCE_CONTRACT_ID) LIKE '%Ê%' THEN CAST(RIHDK2.PAYMENT_AMT AS DECIMAL(23,2))
	WHEN UPPER (AIHDK2.INSURANCE_CONTRACT_ID) LIKE '%A%' THEN CAST(RIHDK2.PAYMENT_AMT AS DECIMAL(23,2))
	WHEN UPPER (AIHDK2.INSURANCE_CONTRACT_ID) LIKE '%À%' THEN CAST(RIHDK2.PAYMENT_AMT AS DECIMAL(23,2))
	ELSE NULL
END AS Ñòðàõ_ïðåìèÿ_ÄÊÀÑÊÎ_ÂÒÁ
--------------------------
,CASE 
	WHEN PROGRAMMA = 'C2C' THEN 1
	WHEN MAK = 'Ìîñêâà' AND UPPER(HOLDING) = 'Õ_ÑÈÌ' THEN 1
	WHEN MAK = 'Ìîñêâà' AND UPPER(HOLDING) = 'Õ_ÀÂÀËÞÊÑ' THEN 1
	WHEN MAK = 'Ìîñêâà' AND UPPER(HOLDING) = 'Õ_ßÕÐÎÌÀ' THEN 1
	WHEN MAK = 'Ìîñêâà' AND UPPER(HOLDING) = 'Õ_ÀÂÒÎÃÀÇ' THEN 1
	WHEN MAK = 'Ìîñêâà' AND UPPER(HOLDING) = 'Õ_ÐÒÐ_ÀÂÒÎ' THEN 1
	WHEN MAK = 'Ìîñêâà' AND UPPER(HOLDING) = 'Õ_ÃÊ_ÁËÎÊ' THEN 1
	WHEN MAK = 'Ìîñêâà' AND UPPER(HOLDING) = 'Õ_ÀÂÈÍÜÎÍ' THEN 1
	WHEN MAK = 'Ìîñêâà' AND UPPER(HOLDING) = 'Õ_ÎÐÅÕÎÂÎ_ÀÂÒÎ_ÖÅÍÒÐ' THEN 1
	WHEN MAK = 'Ìîñêâà' AND UPPER(HOLDING) = 'Õ_ÂÈÑÒ_ÀÂÒÎ' THEN 1
	WHEN MAK = 'Ñàìàðà' AND UPPER(HOLDING) = 'Õ_ÀÑÀÂÒÎ' THEN 1
	WHEN MAK = 'Ñàìàðà' AND UPPER(HOLDING) = 'Õ_ÀÑÀÂÒÎ-ÒÎËÜßÒÒÈ' THEN 1
	WHEN MAK = 'Ñàìàðà' AND UPPER(HOLDING) = 'Õ_ÀÂÒÎÑÀËÎÍ_ÀÑÀÂÒÎ' THEN 1
	WHEN MAK = 'Ñàìàðà' AND UPPER(HOLDING) = 'Õ_ÀÂÒÎ-ÁÐÎÊÅÐ' THEN 1
	WHEN MAK = 'Ñàìàðà' AND UPPER(HOLDING) = 'Õ_ÀÂÒÎÑÀËÎÍ_ÀÐÃÎ' THEN 1
	WHEN MAK = 'Ñàíêò-Ïåòåðáóðã' AND UPPER(HOLDING) = 'Õ_ÀÊÑÅËÜ' THEN 1
	WHEN MAK = 'Ñàíêò-Ïåòåðáóðã' AND UPPER(HOLDING) = 'Õ_ÀÂÐÎÐÀ' THEN 1
	WHEN MAK = 'Ñàíêò-Ïåòåðáóðã' AND UPPER(HOLDING) = 'X_ÀÂÒÎÏÐÎÄÈÊÑ' THEN 1
	WHEN MAK = 'Ñàíêò-Ïåòåðáóðã' AND UPPER(HOLDING) = 'X_ÌÎÍÊÎÌ' THEN 1
	WHEN MAK = 'Êàëèíèíãðàä' AND UPPER(HOLDING) = 'Õ_ÄÈÍÀÌÈÊÀ_ÊÀËÈÍÈÍÃÐ' THEN 1
	WHEN MAK = 'Êàëèíèíãðàä' AND UPPER(HOLDING) = 'Õ_ÄÎ-ÊÀÐ' THEN 1
	WHEN MAK = 'Åêàòåðèíáóðã' AND UPPER(HOLDING) = 'Õ_ÀÑÌÎÒÎ' THEN 1
	WHEN MAK = 'Åêàòåðèíáóðã' AND UPPER(HOLDING) = 'Õ_ÀÂÒÎËÈÄÅÐ' THEN 1
	WHEN MAK = 'Åêàòåðèíáóðã' AND UPPER(HOLDING) = 'Õ_ÁÅÐÅÇÎÂÑÊÈÉ_ÏÐÈÂÎÇ' THEN 1
	WHEN MAK = 'Åêàòåðèíáóðã' AND UPPER(HOLDING) = 'Õ_ÀÌÊ_ÅÊÀÒÅÐÈÍÁÓÐÃ' THEN 1
	WHEN MAK = 'Åêàòåðèíáóðã' AND UPPER(HOLDING) = 'Õ_ÒÐÀÍÑÑÅÐÂÈÑ' THEN 1
	WHEN MAK = 'Åêàòåðèíáóðã' AND UPPER(HOLDING) = 'Õ_ÎÊ_ÒÐÀÍÑ' THEN 1
	WHEN MAK = 'Òþìåíü' AND UPPER(HOLDING) = 'Õ_ÀÂÒÎÃÐÀÄ-ÒÞÌÅÍÜ' THEN 1
	WHEN MAK = 'Òþìåíü' AND UPPER(HOLDING) = 'Õ_ÍÈÊÊÎ' THEN 1
	WHEN MAK = 'Ïåíçà' AND UPPER(HOLDING) = 'Õ_ÑÓÐÀ_ÌÎÒÎÐÑ' THEN 1
	WHEN MAK = 'Ïåíçà' AND UPPER(HOLDING) = 'Õ_ÑÓÐÀ_ÌÎÒÎÐÑ_ÀÂÒÎ' THEN 1
	WHEN MAK = 'Ïåíçà' AND UPPER(HOLDING) = 'Õ_ÀÂÒÎËÎÖÌÀÍ' THEN 1
	WHEN MAK = 'Âîðîíåæ' AND UPPER(HOLDING) = 'Õ_ÐÈÍÃ_ÂÎÐÎÍÅÆ' THEN 1
	WHEN MAK = 'Âîðîíåæ' AND UPPER(HOLDING) = 'Õ_ÁÎÐ_ÀÂÒÎ' THEN 1
	WHEN MAK = 'Âîðîíåæ' AND UPPER(HOLDING) = 'Õ_ÑÎÊÐÀÒ' THEN 1
	WHEN MAK = 'Áåëãîðîä' AND UPPER(HOLDING) = 'Õ_ÄÆÅÍÑÅÐ' THEN 1
	WHEN MAK = 'Èæåâñê' AND UPPER(HOLDING) = 'Õ_ÔÎÐÂÀÐÄ_ÀÂÒÎ' THEN 1
	ELSE 0
END AS MKASKO_znam_flag

FROM CDM_YPDN_NCDN_N72.FCT_AUTO_SALE_DAILY AS ASD

LEFT JOIN	CDM_YPDN_NCDN_N72.cd_internal_org_detail AS CIOD
ON		ASD.init_internal_org_id = CIOD.internal_org_id
AND	CIOD.is_active_flg = '1'

LEFT JOIN	PROD_DAB_URSP_OAPP_SBX.spr_reg_2016 AS SPR
ON		CIOD.regional_office_geography_nm = SPR.regional_office_geography_nm

LEFT JOIN	PROD_DAB_URSP_OAPP_SBX.spr_GAK_2016 AS sprgak
ON 		1=1
AND	CIOD.extra_office_id = sprgak.extra_office_id

LEFT JOIN DDS_YPDN_NCDN_N72.PRODUCT_SUB_HIST AS PSH
ON		1=1
AND	ASD.PRODUCT_SUB_ID = PSH.PRODUCT_SUB_ID
AND	PSH.IS_ACTIVE_FLG = '1'
AND	PSH.DELETED_FLG = '0'

LEFT JOIN	DDS_YPDN_NCDN_N72.dim_vehicle AS DV
ON 	1=1
AND	DV.vehicle_cd = UPPER(ASD.brand_nm)
AND	DV.parent_vehicle_cd = 'ÏÊ-ÌÀÐÊÈÌÎÄÅËÈ'

LEFT JOIN	PROD_DAB_URSP_OAPP_SBX.COOLING_PERIOD AS CPSJ
ON	1=1
AND	CPSJ.CONTRACT_ID = ASD.CONTRACT_ID
AND	CPSJ.INSUR_TYPE = 'ÑÆ'
AND	CPSJ.INSUR_NM = 'ÂÒÁ-Ñ'

LEFT JOIN	PROD_DAB_URSP_OAPP_SBX.COOLING_PERIOD AS CPDK
ON	1=1
AND	CPDK.CONTRACT_ID = ASD.CONTRACT_ID
AND	CPDK.INSUR_TYPE = 'ÄÊÀÑÊÎ'
AND	CPDK.INSUR_NM = 'ÂÒÁ-Ñ'

LEFT JOIN	PROD_DAB_URSP_OAPP_SBX.COOLING_PERIOD AS CPVK
ON	1=1
AND	CPVK.CONTRACT_ID = ASD.CONTRACT_ID
AND	CPVK.INSUR_TYPE = 'ÂìåñòîÊÀÑÊÎ'
AND	CPVK.INSUR_NM = 'ÂÒÁ-Ñ'

LEFT JOIN	PROD_DAB_URSP_OAPP_SBX.COOLING_PERIOD AS CPMK
ON	1=1
AND	CPMK.CONTRACT_ID = ASD.CONTRACT_ID
AND	CPMK.INSUR_TYPE = 'ÌèíèÊÀÑÊÎ'
AND	CPMK.INSUR_NM = 'ÂÒÁ-Ñ'

LEFT JOIN 
(
SELECT * FROM DDS_YPDN_NCDN_N72.AGREEMENT_INSURANCE_HIST AS AIHRAMK
WHERE 1=1
AND	AIHRAMK.EFFECTIVE_TO_DTTM = '5999-12-31 00:00:00'
AND	AIHRAMK.DELETED_FLG = '0'
AND	AIHRAMK.IS_ACTIVE_FLG = '1'
AND	AIHRAMK.EXECUTE_FLG = '1'
AND	AIHRAMK.PARENT_AGREEMENT_TYPE_CD = 'ÊÐÅÄÈÒ'
AND	AIHRAMK.SOURCE_SYSTEM_CD IN ('00040', '00000', '00002', '00056', '00055', '00051', '00018', '00006', '00060')
AND   AIHRAMK.INSURANCE_RISK_TYPE_CD IN ('31', '7') --ÐÀÌÊ
QUALIFY	ROW_NUMBER() OVER (PARTITION BY AIHRAMK.PARENT_AGREEMENT_RK ORDER BY AIHRAMK.EFFECTIVE_FROM_DTTM DESC) = 1	 
) AS AIHRAMK2
ON	AIHRAMK2.PARENT_AGREEMENT_RK = ASD.AGREEMENT_RK

LEFT JOIN 
(
SELECT * FROM DDS_YPDN_NCDN_N72.REPAYMENT_INSURANCE_HIST AS RIHRAMK
WHERE 1=1
AND	RIHRAMK.EFFECTIVE_TO_DTTM = '5999-12-31 00:00:00'
AND	RIHRAMK.DELETED_FLG = '0'
AND	RIHRAMK.IS_ACTIVE_FLG = '1'
AND	RIHRAMK.PAYMENT_FLG = 'ÄÀ'
AND	RIHRAMK.PARENT_AGREEMENT_TYPE_CD = 'ÊÐÅÄÈÒ'
AND	RIHRAMK.SOURCE_SYSTEM_CD IN ('00040', '00000', '00002', '00056', '00055', '00051', '00018', '00006', '00060')
AND   RIHRAMK.INSURANCE_RISK_TYPE_CD IN ('31', '7') --ÐÀÌÊ
QUALIFY	ROW_NUMBER() OVER (PARTITION BY RIHRAMK.PARENT_AGREEMENT_RK ORDER BY RIHRAMK.EFFECTIVE_FROM_DTTM DESC) = 1
) AS RIHRAMK2
ON	RIHRAMK2.PARENT_AGREEMENT_RK = ASD.AGREEMENT_RK

LEFT JOIN 
(
SELECT * FROM DDS_YPDN_NCDN_N72.AGREEMENT_INSURANCE_HIST AS AIHAVL
WHERE 1=1
AND	AIHAVL.EFFECTIVE_TO_DTTM = '5999-12-31 00:00:00'
AND	AIHAVL.DELETED_FLG = '0'
AND	AIHAVL.IS_ACTIVE_FLG = '1'
AND	AIHAVL.EXECUTE_FLG = '1'
AND	AIHAVL.PARENT_AGREEMENT_TYPE_CD = 'ÊÐÅÄÈÒ'
AND	AIHAVL.SOURCE_SYSTEM_CD IN ('00040', '00000', '00002', '00056', '00055', '00051', '00018', '00006', '00060')
AND   AIHAVL.INSURANCE_RISK_TYPE_CD IN ('33', '7') --Àâòîëþáèòåëü
QUALIFY	ROW_NUMBER() OVER (PARTITION BY AIHAVL.PARENT_AGREEMENT_RK ORDER BY AIHAVL.EFFECTIVE_FROM_DTTM DESC) = 1
) AS AIHAVL2
ON	AIHAVL2.PARENT_AGREEMENT_RK = ASD.AGREEMENT_RK

LEFT JOIN 
(
SELECT * FROM DDS_YPDN_NCDN_N72.REPAYMENT_INSURANCE_HIST AS RIHAVL
WHERE 1=1
AND	RIHAVL.EFFECTIVE_TO_DTTM = '5999-12-31 00:00:00'
AND	RIHAVL.DELETED_FLG = '0'
AND	RIHAVL.IS_ACTIVE_FLG = '1'
AND	RIHAVL.PAYMENT_FLG = 'ÄÀ'
AND	RIHAVL.PARENT_AGREEMENT_TYPE_CD = 'ÊÐÅÄÈÒ'
AND	RIHAVL.SOURCE_SYSTEM_CD IN ('00040', '00000', '00002', '00056', '00055', '00051', '00018', '00006', '00060')
AND   RIHAVL.INSURANCE_RISK_TYPE_CD IN ('33', '7') --Àâòîëþáèòåëü
QUALIFY	ROW_NUMBER() OVER (PARTITION BY RIHAVL.PARENT_AGREEMENT_RK ORDER BY RIHAVL.EFFECTIVE_FROM_DTTM DESC) = 1
) AS RIHAVL2
ON	RIHAVL2.PARENT_AGREEMENT_RK = ASD.AGREEMENT_RK

LEFT JOIN 
(
SELECT * FROM DDS_YPDN_NCDN_N72.AGREEMENT_INSURANCE_HIST AS AIHDK
WHERE 1=1
AND	AIHDK.EFFECTIVE_TO_DTTM = '5999-12-31 00:00:00'
AND	AIHDK.DELETED_FLG = '0'
AND	AIHDK.IS_ACTIVE_FLG = '1'
AND	AIHDK.EXECUTE_FLG = '1'
AND	AIHDK.PARENT_AGREEMENT_TYPE_CD = 'ÊÐÅÄÈÒ'
AND	AIHDK.SOURCE_SYSTEM_CD IN ('00040', '00000', '00002', '00056', '00055', '00051', '00018', '00006', '00060')
AND   AIHDK.INSURANCE_RISK_TYPE_CD IN ('32', '7') --ÄÊÀÑÊÎ
QUALIFY	ROW_NUMBER() OVER (PARTITION BY AIHDK.PARENT_AGREEMENT_RK ORDER BY AIHDK.EFFECTIVE_FROM_DTTM DESC) = 1
) AS AIHDK2
ON	AIHDK2.PARENT_AGREEMENT_RK = ASD.AGREEMENT_RK

LEFT JOIN 
(
SELECT * FROM DDS_YPDN_NCDN_N72.REPAYMENT_INSURANCE_HIST AS RIHDK
WHERE 1=1
AND	RIHDK.EFFECTIVE_TO_DTTM = '5999-12-31 00:00:00'
AND	RIHDK.DELETED_FLG = '0'
AND	RIHDK.IS_ACTIVE_FLG = '1'
AND	RIHDK.PAYMENT_FLG = 'ÄÀ'
AND	RIHDK.PARENT_AGREEMENT_TYPE_CD = 'ÊÐÅÄÈÒ'
AND	RIHDK.SOURCE_SYSTEM_CD IN ('00040', '00000', '00002', '00056', '00055', '00051', '00018', '00006', '00060')
AND   RIHDK.INSURANCE_RISK_TYPE_CD IN ('32', '7') --ÄÊÀÑÊÎ
QUALIFY	ROW_NUMBER() OVER (PARTITION BY RIHDK.PARENT_AGREEMENT_RK ORDER BY RIHDK.EFFECTIVE_FROM_DTTM DESC) = 1
) AS RIHDK2
ON	RIHDK2.PARENT_AGREEMENT_RK = ASD.AGREEMENT_RK

LEFT JOIN CDM_YPDN_NCDN_N72.AGG_BP_LOAN_ISSUE AS ABLI
ON ASD.CONTRACT_ID = ABLI.CONTRACT_ID
AND ABLI.PLAN_ALGORITHM_VERSION = '3'
AND ABLI.ISSUE_AMT > 0

WHERE 1=1
AND ASD.ISSUE_DT BETWEEN '2017-10-01' AND (SELECT (DATE-DAY_OF_WEEK(DATE))+0)                --(SELECT (DATE-DAY_OF_WEEK(DATE))+1) --- Ìåíÿåì Äàòó íà òåêóùóþ--(LAST SUNDAY)
AND ASD.PRODUCT_OPERATIONAL_ID IN ('ÀÑ','ÀË','ÀÝ','ÀÁ','ÀÏ','À1','À2','À5','ÀÓ','ÀÎ')





