--Select your dates for fact
DROP TABLE SELECT_DATE_FACT;
CREATE VOLATILE TABLE SELECT_DATE_FACT AS 
(
SELECT 
'2017-10-01' AS DATE_FROM
,'2017-10-31' AS DATE_TO
) 
WITH DATA PRIMARY INDEX (DATE_FROM, DATE_TO)
ON COMMIT PRESERVE ROWS;

--Select your dates for plan
DROP TABLE SELECT_DATE_PLAN;
CREATE VOLATILE TABLE SELECT_DATE_PLAN AS 
(
SELECT 
'2017-10-01' AS DATE_FROM
,'2017-10-31' AS DATE_TO
)
WITH DATA PRIMARY INDEX (DATE_FROM, DATE_TO)
ON COMMIT PRESERVE ROWS;

--панель для расчета проникновения по СУ
CALL _DOMAIN_.DROP_TABLE('pt_SU_PANEL');
---				SELECT * FROM _DOMAIN_.pt_SU_PANEL
CREATE TABLE _DOMAIN_.pt_SU_PANEL AS
(
SELECT
CASE WHEN CIOD.extra_office_id IN ('0019', '0119', '0219', '1019', '1219', '1119', '1319', '1419', '1519', '1719') THEN 'Тольятти' 
	WHEN CIOD.extra_office_id IN ('1015', '1815', '2915', '1115') THEN 'Тюмень' 
	WHEN CIOD.extra_office_id IN ('4215', '2315', '1415', '3015', '2715') THEN 'Сургут'
	WHEN CIOD.extra_office_id IN ('2464') THEN 'Уфа'	
ELSE SPR.mak_nm END AS MAK -- Города МАК
,ASD.CONTRACT_ID AS DOGOVOR -- Номер кредитного договора	
,ASD.ISSUE_DT AS DTV -- Дата выдачи
,ASD.LOAN_RUR_AMT AS LOAN_RUR_AMT_FULL --- Полная сумма выдачи в рублях
,CASE WHEN ASD.PRODUCT_OPERATIONAL_ID IN  ('А1','А2','А5') THEN 'АЭ' ELSE ASD.PRODUCT_OPERATIONAL_ID END PRODUCT --Продукт

---	АвтоКАСКО + ВместоКАСКО ()
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '6' THEN Insur.INSURANCE_COMPANY_FULL_NM ELSE NULL END) AS COMPREH_COVER_INSURANT_NM	
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '6' THEN Insur.OPEN_DT ELSE NULL END) AS COMPREH_COVER_OPEN_DT
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '6' THEN Insur.INSURANCE_AGREEMENT_ID ELSE NULL END) AS COMPREH_COVER_CONTRACT_ID
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '6' THEN Insur.PAYMENT_AMT ELSE NULL END) AS COMPREH_COVER_PAYMENT_RUR_AMT
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '6' THEN Insur.INSURANCE_PAYMENT_WAY_DESC ELSE NULL END) AS COMPREH_INSUR_PAYMENT_DESC
/*	Страховая услуга ОСАГО, ДАБ не используется для учета.
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '7' THEN Insur.INSURANCE_COMPANY_FULL_NM ELSE NULL END) AS COMPULS_INSUR_INSURANT_NM	
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '7' THEN Insur.OPEN_DT ELSE NULL END) AS COMPULS_INSUR_OPEN_DT
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '7' THEN Insur.INSURANCE_AGREEMENT_ID ELSE NULL END) AS COMPULS_INSUR_CONTRACT_ID
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '7' THEN Insur.PAYMENT_AMT ELSE NULL END) AS COMPULS_INSUR_PAYMENT_RUR_AMT
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '7' THEN Insur.INSURANCE_PAYMENT_WAY_DESC ELSE NULL END) AS COMPULS_INSUR_PAYMENT_DESC	*/
---	Страхование жизни
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '13' THEN Insur.INSURANCE_COMPANY_FULL_NM ELSE NULL END) AS LIFE_INSURANCE_INSURANT_NM	
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '13' THEN Insur.OPEN_DT ELSE NULL END) AS LIFE_INSURANCE_OPEN_DT
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '13' THEN Insur.INSURANCE_AGREEMENT_ID ELSE NULL END) AS LIFE_INSURANCE_CONTRACT_ID
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '13' THEN Insur.PAYMENT_AMT ELSE NULL END) AS LIFE_INSURANCE_PAYMENT_RUR_AMT
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '13' THEN Insur.INSURANCE_PAYMENT_WAY_DESC ELSE NULL END) AS LIFE_INSUR_PAYMENT_DESC
---	Поле "Иное"
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '30' THEN Insur.INSURANCE_COMPANY_FULL_NM ELSE NULL END) AS OTHER_INSURANT_NM	
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '30' THEN Insur.OPEN_DT ELSE NULL END) AS OTHER_OPEN_DT
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '30' THEN Insur.INSURANCE_AGREEMENT_ID ELSE NULL END) AS OTHER_CONTRACT_ID
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '30' THEN Insur.PAYMENT_AMT ELSE NULL END) AS OTHER_PAYMENT_RUR_AMT
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '30' THEN Insur.INSURANCE_PAYMENT_WAY_DESC ELSE NULL END) AS OTHER_INSUR_PAYMENT_DESC
---	РАМК "Помощь на дорогах" 
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '31' THEN Insur.INSURANCE_COMPANY_FULL_NM ELSE NULL END) AS RAMK_INSURANT_NM	
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '31' THEN Insur.OPEN_DT ELSE NULL END) AS RAMK_OPEN_DT
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '31' THEN Insur.INSURANCE_AGREEMENT_ID ELSE NULL END) AS RAMK_CONTRACT_ID
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '31' THEN Insur.PAYMENT_AMT ELSE NULL END) AS RAMK_PAYMENT_RUR_AMT
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '31' THEN Insur.INSURANCE_PAYMENT_WAY_DESC ELSE NULL END) AS RAMK_INSUR_PAYMENT_DESC
---	ДКАСКО
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '32' THEN Insur.INSURANCE_COMPANY_FULL_NM ELSE NULL END) AS DKASKO_INSURANT_NM	
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '32' THEN Insur.OPEN_DT ELSE NULL END) AS DKASKO_OPEN_DT
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '32' THEN Insur.INSURANCE_AGREEMENT_ID ELSE NULL END) AS DKASKO_CONTRACT_ID
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '32' THEN Insur.PAYMENT_AMT ELSE NULL END) AS DKASKO_PAYMENT_RUR_AMT
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '32' THEN Insur.INSURANCE_PAYMENT_WAY_DESC ELSE NULL END) AS DKASKO_INSUR_PAYMENT_DESC
---	Карта АВТОЛЮБИТЕЛЬ
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '33' THEN Insur.INSURANCE_COMPANY_FULL_NM ELSE NULL END) AS AVL_INSURANT_NM	
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '33' THEN Insur.OPEN_DT ELSE NULL END) AS AVL_OPEN_DT
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '33' THEN Insur.INSURANCE_AGREEMENT_ID ELSE NULL END) AS AVL_CONTRACT_ID
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '33' THEN Insur.PAYMENT_AMT ELSE NULL END) AS AVL_PAYMENT_RUR_AMT
,	MAX(CASE WHEN Insur.INSURANCE_RISK_TYPE_CD = '33' THEN Insur.INSURANCE_PAYMENT_WAY_DESC ELSE NULL END) AS AVL_INSUR_PAYMENT_DESC

FROM _DOMAINN_._TABLE1_ AS ASD     -- данные о выданных автокредитах

LEFT JOIN _DOMAINN_._TABLE2_ AS Insur
		ON 1=1
			AND Insur.AGREEMENT_RK = ASD.AGREEMENT_RK
			AND Insur.EFFECTIVE_TO_DTTM = CAST('5999-12-31 00:00:00' AS TIMESTAMP(0))
			AND Insur.DELETED_FLG = '0' 

LEFT JOIN	_DOMAINN_._TABLE3_ AS CIOD
ON		ASD.INIT_INTERNAL_ORG_ID = CIOD.INTERNAL_ORG_ID
AND	CIOD.IS_ACTIVE_FLG = '1'

LEFT JOIN	_DOMAIN_.SPR_REG_2016 AS SPR
ON		CIOD.REGIONAL_OFFICE_GEOGRAPHY_NM = SPR.REGIONAL_OFFICE_GEOGRAPHY_NM

WHERE 1=1
AND ASD.PRODUCT_OPERATIONAL_ID IN ('АС','АЛ','АЭ','АП','А1','А2','А5','АУ','АО','АБ')
AND ASD.ISSUE_DT BETWEEN (CAST(SELECT_DATE_FACT.DATE_FROM AS DATE)) AND (CAST(SELECT_DATE_FACT.DATE_TO AS DATE))
GROUP BY MAK, DOGOVOR, DTV, LOAN_RUR_AMT_FULL, PRODUCT
) WITH DATA PRIMARY INDEX(DOGOVOR);

--расчет проникновения по СУ
CALL _DOMAIN_.DROP_TABLE('pt_SU_PENETRATION');
---				SELECT * FROM _DOMAIN_.pt_SU_PENETRATION
CREATE TABLE _DOMAIN_.pt_SU_PENETRATION AS
(
SELECT
MAC_SPISOK.MAK AS MAC
---	ВместоКАСКО ()
,SUP_VK_LJ.VKASKO_PENET_SHT
,SUP_VK_LJ.VKASKO_PENET_RUB
---	МиниКАСКО (от компании ВТБ-С)
,SUP_MK_LJ.MKASKO_PENET_SHT
,SUP_MK_LJ.MKASKO_PENET_RUB
---	Страхование жизни
,SUP_SJ_LJ.SJ_PENET_SHT
,SUP_SJ_LJ.SJ_PENET_RUB
---	ДКАСКО
,SUP_DK_LJ.DKASKO_PENET_SHT
,SUP_DK_LJ.DKASKO_PENET_RUB
---	РАМК "Помощь на дорогах"
,SUP_RAMK_LJ.RAMK_PENET_SHT
,SUP_RAMK_LJ.RAMK_PENET_RUB
---	Карта АВТОЛЮБИТЕЛЬ
,SUP_AVL_LJ.AVL_PENET_SHT
,SUP_AVL_LJ.AVL_PENET_RUB
FROM (SELECT DISTINCT(MAK) FROM _DOMAIN_.pt_SU_PANEL) AS MAC_SPISOK
--ВместоКАСКО ()
LEFT JOIN 
(
	SELECT
	SUP_VK.MAK AS MAC
	,CAST(COUNT(SUP_VK.DOGOVOR) AS DECIMAL(38,6)) AS DOGOVOR_CNT
	,CAST(SUM(SUP_VK.LOAN_RUR_AMT_FULL) AS DECIMAL(38,6)) AS LOAN_RUR_AMT_FULL_SUM
	---	ВместоКАСКО ()
	,SUM(CASE 
					WHEN SUP_VK.COMPREH_COVER_INSURANT_NM LIKE '%КАРДИФ%' AND SUP_VK.COMPREH_COVER_CONTRACT_ID IS NOT NULL THEN 1 
					WHEN UPPER(SUP_VK.COMPREH_COVER_INSURANT_NM) LIKE '%ВТБ%' AND SUP_VK.COMPREH_COVER_CONTRACT_ID LIKE '%А342%' AND SUP_VK.COMPREH_COVER_CONTRACT_ID IS NOT NULL THEN 1 --кириллица
					WHEN UPPER(SUP_VK.COMPREH_COVER_INSURANT_NM) LIKE '%ВТБ%' AND SUP_VK.COMPREH_COVER_CONTRACT_ID LIKE '%A342%' AND SUP_VK.COMPREH_COVER_CONTRACT_ID IS NOT NULL THEN 1 --латиница
					ELSE 0 END) 
		AS VKASKO_CNT
	,SUM(CASE 
					WHEN SUP_VK.COMPREH_COVER_INSURANT_NM LIKE '%КАРДИФ%' AND SUP_VK.COMPREH_COVER_CONTRACT_ID IS NOT NULL THEN SUP_VK.LOAN_RUR_AMT_FULL 
					WHEN UPPER(SUP_VK.COMPREH_COVER_INSURANT_NM) LIKE '%ВТБ%' AND SUP_VK.COMPREH_COVER_CONTRACT_ID LIKE '%А342%' AND SUP_VK.COMPREH_COVER_CONTRACT_ID IS NOT NULL THEN SUP_VK.LOAN_RUR_AMT_FULL --кириллица
					WHEN UPPER(SUP_VK.COMPREH_COVER_INSURANT_NM) LIKE '%ВТБ%' AND SUP_VK.COMPREH_COVER_CONTRACT_ID LIKE '%A342%' AND SUP_VK.COMPREH_COVER_CONTRACT_ID IS NOT NULL THEN SUP_VK.LOAN_RUR_AMT_FULL --латиница
					ELSE 0 END) 
		AS VKASKO_SUM
	,(CAST(VKASKO_CNT AS DECIMAL(38,6)))/(CAST(DOGOVOR_CNT AS DECIMAL(38,6))) AS VKASKO_PENET_SHT
	,VKASKO_SUM/LOAN_RUR_AMT_FULL_SUM AS VKASKO_PENET_RUB
	FROM _DOMAIN_.pt_SU_PANEL AS SUP_VK
	WHERE 1=1
	AND SUP_VK.PRODUCT NOT IN ('АБ')
	GROUP BY MAC
) AS SUP_VK_LJ
ON MAC_SPISOK.MAK = SUP_VK_LJ.MAC
--МиниКАСКО (от компании ВТБ-С)
LEFT JOIN 
(
	SELECT
	SUP_MK.MAK AS MAC
	,CAST(COUNT(SUP_MK.DOGOVOR) AS DECIMAL(38,6)) AS DOGOVOR_CNT
	,CAST(SUM(SUP_MK.LOAN_RUR_AMT_FULL) AS DECIMAL(38,6)) AS LOAN_RUR_AMT_FULL_SUM
	---	МиниКАСКО (от компании ВТБ-С)
	,SUM(CASE WHEN SUP_MK.COMPREH_COVER_INSURANT_NM LIKE '%ВТБ%' AND SUP_MK.COMPREH_INSUR_PAYMENT_DESC LIKE '%за счет%' AND SUP_MK.COMPREH_COVER_CONTRACT_ID IS NOT NULL THEN 1 ELSE 0 END) AS MKASKO_CNT
	,SUM(CASE WHEN SUP_MK.COMPREH_COVER_INSURANT_NM LIKE '%ВТБ%' AND SUP_MK.COMPREH_INSUR_PAYMENT_DESC LIKE '%за счет%' AND SUP_MK.COMPREH_COVER_CONTRACT_ID IS NOT NULL THEN SUP_MK.LOAN_RUR_AMT_FULL ELSE 0 END) AS MKASKO_SUM
	,(CAST(MKASKO_CNT AS DECIMAL(38,6)))/(CAST(DOGOVOR_CNT AS DECIMAL(38,6))) AS MKASKO_PENET_SHT
	,MKASKO_SUM/LOAN_RUR_AMT_FULL_SUM AS MKASKO_PENET_RUB
	FROM _DOMAIN_.pt_SU_PANEL AS SUP_MK
	WHERE 1=1
	GROUP BY MAC
) AS SUP_MK_LJ
ON MAC_SPISOK.MAK = SUP_MK_LJ.MAC
--Страхование жизни
LEFT JOIN 
(
	SELECT
	SUP_SJ.MAK AS MAC
	,CAST(COUNT(SUP_SJ.DOGOVOR) AS DECIMAL(38,6)) AS DOGOVOR_CNT
	,CAST(SUM(SUP_SJ.LOAN_RUR_AMT_FULL) AS DECIMAL(38,6)) AS LOAN_RUR_AMT_FULL_SUM
	---	Страхование жизни
	,SUM(CASE WHEN SUP_SJ.LIFE_INSURANCE_CONTRACT_ID IS NOT NULL THEN 1 ELSE 0 END) AS SJ_CNT
	,SUM(CASE WHEN SUP_SJ.LIFE_INSURANCE_CONTRACT_ID IS NOT NULL THEN SUP_SJ.LOAN_RUR_AMT_FULL ELSE 0 END) AS SJ_SUM
	,(CAST(SJ_CNT AS DECIMAL(38,6)))/(CAST(DOGOVOR_CNT AS DECIMAL(38,6))) AS SJ_PENET_SHT
	,SJ_SUM/LOAN_RUR_AMT_FULL_SUM AS SJ_PENET_RUB
	FROM _DOMAIN_.pt_SU_PANEL AS SUP_SJ
	WHERE 1=1
	GROUP BY MAC
) AS SUP_SJ_LJ
ON MAC_SPISOK.MAK = SUP_SJ_LJ.MAC
--ДКАСКО
LEFT JOIN 
(
	SELECT
	SUP_DK.MAK AS MAC
	,CAST(COUNT(SUP_DK.DOGOVOR) AS DECIMAL(38,6)) AS DOGOVOR_CNT
	,CAST(SUM(SUP_DK.LOAN_RUR_AMT_FULL) AS DECIMAL(38,6)) AS LOAN_RUR_AMT_FULL_SUM
	---	ДКАСКО
	,SUM(CASE WHEN SUP_DK.DKASKO_CONTRACT_ID IS NOT NULL THEN 1 ELSE 0 END) AS DKASKO_CNT
	,SUM(CASE WHEN SUP_DK.DKASKO_CONTRACT_ID IS NOT NULL THEN SUP_DK.LOAN_RUR_AMT_FULL ELSE 0 END) AS DKASKO_SUM
	,(CAST(DKASKO_CNT AS DECIMAL(38,6)))/(CAST(DOGOVOR_CNT AS DECIMAL(38,6))) AS DKASKO_PENET_SHT
	,DKASKO_SUM/LOAN_RUR_AMT_FULL_SUM AS DKASKO_PENET_RUB
	FROM _DOMAIN_.pt_SU_PANEL AS SUP_DK
	WHERE 1=1
	AND SUP_DK.PRODUCT NOT IN ('АБ')
	GROUP BY MAC
) AS SUP_DK_LJ
ON MAC_SPISOK.MAK = SUP_DK_LJ.MAC
--РАМК "Помощь на дорогах"
LEFT JOIN 
(
	SELECT
	SUP_RAMK.MAK AS MAC
	,CAST(COUNT(SUP_RAMK.DOGOVOR) AS DECIMAL(38,6)) AS DOGOVOR_CNT
	,CAST(SUM(SUP_RAMK.LOAN_RUR_AMT_FULL) AS DECIMAL(38,6)) AS LOAN_RUR_AMT_FULL_SUM
	---	РАМК "Помощь на дорогах"
	,SUM(CASE WHEN SUP_RAMK.RAMK_INSURANT_NM LIKE '%АвтоМотоКлуб%' AND SUP_RAMK.RAMK_CONTRACT_ID IS NOT NULL THEN 1 ELSE 0 END) AS RAMK_CNT
	,SUM(CASE WHEN SUP_RAMK.RAMK_INSURANT_NM LIKE '%АвтоМотоКлуб%' AND SUP_RAMK.RAMK_CONTRACT_ID IS NOT NULL THEN SUP_RAMK.LOAN_RUR_AMT_FULL ELSE 0 END) AS RAMK_SUM
	,(CAST(RAMK_CNT AS DECIMAL(38,6)))/(CAST(DOGOVOR_CNT AS DECIMAL(38,6))) AS RAMK_PENET_SHT
	,RAMK_SUM/LOAN_RUR_AMT_FULL_SUM AS RAMK_PENET_RUB
	FROM _DOMAIN_.pt_SU_PANEL AS SUP_RAMK
	WHERE 1=1
	GROUP BY MAC
) AS SUP_RAMK_LJ
ON MAC_SPISOK.MAK = SUP_RAMK_LJ.MAC
---	Карта АВТОЛЮБИТЕЛЬ
LEFT JOIN 
(
	SELECT
	SUP_AVL.MAK AS MAC
	,CAST(COUNT(SUP_AVL.DOGOVOR) AS DECIMAL(38,6)) AS DOGOVOR_CNT
	,CAST(SUM(SUP_AVL.LOAN_RUR_AMT_FULL) AS DECIMAL(38,6)) AS LOAN_RUR_AMT_FULL_SUM
	---	Карта АВТОЛЮБИТЕЛЬ
	,SUM(CASE WHEN SUP_AVL.AVL_CONTRACT_ID IS NOT NULL THEN 1 ELSE 0 END) AS AVL_CNT
	,SUM(CASE WHEN SUP_AVL.AVL_CONTRACT_ID IS NOT NULL THEN SUP_AVL.LOAN_RUR_AMT_FULL ELSE 0 END) AS AVL_SUM
	,(CAST(AVL_CNT AS DECIMAL(38,6)))/(CAST(DOGOVOR_CNT AS DECIMAL(38,6))) AS AVL_PENET_SHT
	,AVL_SUM/LOAN_RUR_AMT_FULL_SUM AS AVL_PENET_RUB
	FROM _DOMAIN_.pt_SU_PANEL AS SUP_AVL
	WHERE 1=1
	GROUP BY MAC
) AS SUP_AVL_LJ
ON MAC_SPISOK.MAK = SUP_AVL_LJ.MAC
WHERE 1=1
) WITH DATA PRIMARY INDEX(MAC);

--панель для расчета среднего веса
CALL _DOMAIN_.DROP_TABLE('pt_SRED_VES_PANEL');
---				SELECT * FROM _DOMAIN_.pt_SRED_VES_PANEL
CREATE TABLE _DOMAIN_.pt_SRED_VES_PANEL AS
(
SELECT
ASD.CONTRACT_ID AS DOGOVOR
,CASE WHEN CIOD.extra_office_id IN ('0019', '0119', '0219', '1019', '1219', '1119', '1319', '1419', '1519', '1719') THEN 'Тольятти' 
	WHEN CIOD.extra_office_id IN ('1015', '1815', '2915', '1115') THEN 'Тюмень' 
	WHEN CIOD.extra_office_id IN ('4215', '2315', '1415', '3015', '2715') THEN 'Сургут'
	WHEN CIOD.extra_office_id IN ('2464') THEN 'Уфа'	
ELSE SPR.mak_nm END AS MAK -- Города МАК
,ASD.LOAN_RUR_AMT
,ASD.VEHICLE_COST_RUR_AMT
,(CASE
        WHEN ASD.product_sub_id LIKE '%ГП%' AND ASD.product_operational_id NOT IN ('АБ') AND ASD.product_sub_nm LIKE '%суб.6,7%' THEN ASD.interest_rate + CAST(6.70 AS DECIMAL(23,2))
		WHEN ASD.product_sub_id LIKE '%ГП%' AND ASD.product_operational_id NOT IN ('АБ') AND ASD.issue_dt BETWEEN '2015-04-01' AND '2015-05-04' THEN ASD.interest_rate + CAST(9.33 AS DECIMAL(23,2))
        WHEN ASD.product_sub_id LIKE '%ГП%' AND ASD.product_operational_id NOT IN ('АБ') AND ASD.issue_dt BETWEEN '2015-05-05' AND '2015-06-15' THEN ASD.interest_rate + CAST(8.33 AS DECIMAL(23,2))
        WHEN ASD.product_sub_id LIKE '%ГП%' AND ASD.product_operational_id NOT IN ('АБ') AND  ASD.issue_dt BETWEEN '2015-06-16' AND '2015-08-02'  THEN ASD.interest_rate + CAST(7.67 AS DECIMAL(23,2))
        WHEN ASD.product_sub_id LIKE '%ГП%' AND ASD.product_operational_id NOT IN ('АБ') AND  ASD.issue_dt BETWEEN '2015-08-03' AND '2016-06-13'  THEN ASD.interest_rate + CAST(7.33 AS DECIMAL(23,2))
        WHEN ASD.product_sub_id LIKE '%ГП%' AND ASD.product_operational_id NOT IN ('АБ') AND  ASD.issue_dt BETWEEN '2016-06-14' AND '2016-09-18'  THEN ASD.interest_rate + CAST(7.00 AS DECIMAL(23,2))
        WHEN ASD.product_sub_id LIKE '%ГП%' AND ASD.product_operational_id NOT IN ('АБ') AND  ASD.issue_dt BETWEEN '2016-09-19' AND '2017-03-26'  THEN ASD.interest_rate + CAST(6.67 AS DECIMAL(23,2))
        WHEN ASD.product_sub_id LIKE '%ГП%' AND ASD.product_operational_id NOT IN ('АБ') AND  ASD.issue_dt BETWEEN '2017-03-27' AND '2017-05-01'  THEN ASD.interest_rate + CAST(6.50 AS DECIMAL(23,2))
        WHEN ASD.product_sub_id LIKE '%ГП%' AND ASD.product_operational_id NOT IN ('АБ') AND  ASD.issue_dt BETWEEN '2017-05-02' AND '2017-06-30'  THEN ASD.interest_rate + CAST(6.17 AS DECIMAL(23,2))
		WHEN ASD.product_sub_id LIKE '%ГП%' AND ASD.product_operational_id NOT IN ('АБ') AND  ASD.issue_dt BETWEEN '2017-07-01' AND '2017-12-31'  THEN ASD.interest_rate + CAST(6.70 AS DECIMAL(23,2))
        ELSE ASD.interest_rate
END) AS StavkaGP	-- % ставка с учётом ГП
,ASD.CONTRACT_PERIOD AS SROKKRED -- Срок кредитования
,(ASD.VEHICLE_COST_RUR_AMT - ASD.CAR_LOAN_RUR_AMT)/ASD.VEHICLE_COST_RUR_AMT AS PV

FROM _DOMAINN_._TABLE1_ AS ASD

LEFT JOIN _DOMAINN_._TABLE3_ AS CIOD
ON		ASD.INIT_INTERNAL_ORG_ID = CIOD.INTERNAL_ORG_ID
AND	CIOD.IS_ACTIVE_FLG = '1'

LEFT JOIN _DOMAIN_.SPR_REG_2016 AS SPR
ON		CIOD.REGIONAL_OFFICE_GEOGRAPHY_NM = SPR.REGIONAL_OFFICE_GEOGRAPHY_NM

WHERE 1=1
AND ASD.ISSUE_DT BETWEEN SELECT_DATE_FACT.DATE_FROM AND SELECT_DATE_FACT.DATE_TO --Период факта выдач должен = периоду плана
AND ASD.PRODUCT_OPERATIONAL_ID IN ('АС','АЛ','АЭ','АБ','АП','А1','А2','А5','АУ','АО')
) WITH DATA PRIMARY INDEX (DOGOVOR);

--расчет среднего веса
CALL _DOMAIN_.DROP_TABLE('pt_SRED_VES');
---				SELECT * FROM _DOMAIN_.pt_SRED_VES
CREATE TABLE _DOMAIN_.pt_SRED_VES AS
(
SELECT
SVP.MAK AS MAC
,SUM(SVP.StavkaGP * SVP.LOAN_RUR_AMT) AS SUM_STAVKAGP
,SUM(SVP.SROKKRED * SVP.LOAN_RUR_AMT) AS SUM_SROKKRED
,SUM(SVP.PV * SVP.VEHICLE_COST_RUR_AMT) AS SUM_PV
,SUM_STAVKAGP/SUM(SVP.LOAN_RUR_AMT) AS SV_STAVKAGP
,SUM_SROKKRED/SUM(SVP.LOAN_RUR_AMT) AS SV_SROKKRED
,SUM_PV/SUM(SVP.VEHICLE_COST_RUR_AMT) AS SV_PV
,SUM(SVP.VEHICLE_COST_RUR_AMT) AS SV_VEH_COST
FROM _DOMAIN_.pt_SRED_VES_PANEL AS SVP
WHERE 1=1
GROUP BY MAC
) WITH DATA PRIMARY INDEX (MAC);

--Final Export
----------------------------------
SELECT

SELECT_DATE_FACT.DATE_FROM
,SELECT_DATE_FACT.DATE_TO
,CASE WHEN CIOD.extra_office_id IN ('0019', '0119', '0219', '1019', '1219', '1119', '1319', '1419', '1519', '1719') THEN 'Тольятти' 
	WHEN CIOD.extra_office_id IN ('1015', '1815', '2915', '1115') THEN 'Тюмень' 
	WHEN CIOD.extra_office_id IN ('4215', '2315', '1415', '3015', '2715') THEN 'Сургут'
	WHEN CIOD.extra_office_id IN ('2464') THEN 'Уфа'	
ELSE SPR.mak_nm END AS MAK -- Города МАК
,DBP_COUNT.PLAN_COUNT AS TOTAL_COUNT_PLAN --План тотал штуки
,COUNT(ASD.CONTRACT_ID) AS TOTAL_COUNT_FACT --Факт тотал выдач штуки
,TOTAL_COUNT_FACT/TOTAL_COUNT_PLAN AS ISPOL_PLANA_COUNT --Исполнение тотал плана в штуках

,DBP_SUM.PLAN_COUNT AS TOTAL_SUM_PLAN --План тотал рубли
,SUM(ASD.LOAN_RUR_AMT) AS TOTAL_SUM_FACT --Факт тотал выдач рубли
,TOTAL_SUM_FACT/TOTAL_SUM_PLAN AS ISPOL_PLANA_SUM --Исполнение тотал плана в рублях
,AVERAGE(ASD.LOAN_RUR_AMT) AS MEDIUM_CHECK --Средний чек факт

,PFP.FP_PLAN_COUNT AS FP_COUNT_PLAN --План штуки ФП
,FFP.FP_COUNT_FACT AS FP_COUNT_FACT --Факт штуки ФП
,FP_COUNT_FACT/FP_COUNT_PLAN AS ISPOL_PLANA_FP --Исполнение плана ФП в штуках

,PneFP_SHORT.neFP_COUNT_PLAN_LJ AS neFP_COUNT_PLAN --План штуки неФП
,FneFP.neFP_COUNT_FACT AS neFP_COUNT_FACT --Факт штуки неФП
,neFP_COUNT_FACT/neFP_COUNT_PLAN AS ISPOL_PLANA_neFP --Исполнение плана неФП в штуках

,ASP_DP.PLAN_COUNT AS ASP_D_COUNT_PLAN --План штуки АСП_дилеры
,ASP_DF.ASP_DEALERS_COUNT_FACT AS ASP_D_COUNT_FACT --Факт штуки АСП_дилеры
,ASP_D_COUNT_FACT/ASP_D_COUNT_PLAN AS ISPOL_PLANA_ASP_D --Исполнение плана АСП_дилеры

,PLAN_C2C.PLAN_COUNT AS C2C_COUNT_PLAN --План штуки C2C
,COALESCE(FACT_C2C.C2C_COUNT_FACT,0) AS C2C_COUNT_FACT --Факт штуки C2C
,CASE WHEN C2C_COUNT_PLAN = 0 THEN 0 ELSE COALESCE(C2C_COUNT_FACT/C2C_COUNT_PLAN,0) END AS ISPOL_PLANA_C2C --Исполнение плана C2C

,SUP.VKASKO_PENET_SHT --Проникновение ВместоКАСКО по штукам
,SUP.VKASKO_PENET_RUB --Проникновение ВместоКАСКО по рублям
,SUP.MKASKO_PENET_SHT --Проникновение МиниКАСКО по штукам
,SUP.MKASKO_PENET_RUB --Проникновение МиниКАСКО по рублям
,SUP.SJ_PENET_SHT --Проникновение СЖ по штукам
,SUP.SJ_PENET_RUB --Проникновение СЖ по рублям
,SUP.DKASKO_PENET_SHT --Проникновение ДКАСКО по штукам
,SUP.DKASKO_PENET_RUB --Проникновение ДКАСКО по рублям
,SUP.RAMK_PENET_SHT --Проникновение РАМК по штукам
,SUP.RAMK_PENET_RUB --Проникновение РАМК по рублям
,SUP.AVL_PENET_SHT --Проникновение АВЛ по штукам
,SUP.AVL_PENET_RUB --Проникновение АВЛ по рублям

,SV.SV_STAVKAGP -- % ставка с учётом ГП
,SV.SV_SROKKRED --Срок кредитования (месяцы)

,PLAN_AB.PLAN_COUNT AS AB_COUNT_PLAN --План штуки АБ
,COALESCE(FACT_AB.AB_COUNT_FACT, 0) AS AB_COUNT_FACT --Факт выдач АБ штуки
,SV.SV_PV --% первоначального взноса
,SV.SV_VEH_COST

FROM _DOMAINN_._TABLE1_ AS ASD

LEFT JOIN _DOMAINN_._TABLE3_ AS CIOD
ON		ASD.INIT_INTERNAL_ORG_ID = CIOD.INTERNAL_ORG_ID
AND	CIOD.IS_ACTIVE_FLG = '1'

LEFT JOIN _DOMAIN_.SPR_REG_2016 AS SPR
ON		CIOD.REGIONAL_OFFICE_GEOGRAPHY_NM = SPR.REGIONAL_OFFICE_GEOGRAPHY_NM

--План тотал в штуках
LEFT JOIN 
(
SELECT 
MAC
,SUM(VALUE_AMT) AS PLAN_COUNT --Период плана
FROM _DOMAIN_.pt_BusinessPlanTotal_vanilla
WHERE 1=1
AND METRIC_NAME = 'выдачи,шт.'
AND DATE_SYS BETWEEN SELECT_DATE_PLAN.DATE_FROM AND SELECT_DATE_PLAN.DATE_TO --Период плана
GROUP BY MAC
) AS DBP_COUNT
ON MAK = DBP_COUNT.MAC

--План тотал в рублях
LEFT JOIN 
(
SELECT
MAC
,SUM(VALUE_AMT)*1000 AS PLAN_COUNT --Период плана
FROM _DOMAIN_.pt_BusinessPlanTotal_vanilla
WHERE 1=1
AND METRIC_NAME = 'выдачи,тыс.руб.'
AND DATE_SYS BETWEEN SELECT_DATE_PLAN.DATE_FROM AND SELECT_DATE_PLAN.DATE_TO --Период плана
GROUP BY MAC
) AS DBP_SUM
ON MAK = DBP_SUM.MAC

--План ФП штуки
LEFT JOIN
(
SELECT 
MAC
,SUM(VALUE_CNT) AS FP_PLAN_COUNT
FROM _DOMAIN_.pt_BusinessPlanFP_vanilla
WHERE 1=1
AND DATE_SYS BETWEEN SELECT_DATE_PLAN.DATE_FROM AND SELECT_DATE_PLAN.DATE_TO --Период плана
GROUP BY MAC
) AS PFP
ON MAK = PFP.MAC

--Факт ФП штуки
LEFT JOIN
(
SELECT
CASE WHEN CIOD.extra_office_id IN ('0019', '0119', '0219', '1019', '1219', '1119', '1319', '1419', '1519', '1719') THEN 'Тольятти' 
	WHEN CIOD.extra_office_id IN ('1015', '1815', '2915', '1115') THEN 'Тюмень' 
	WHEN CIOD.extra_office_id IN ('4215', '2315', '1415', '3015', '2715') THEN 'Сургут' 
ELSE SPR.mak_nm END AS MAC -- Города МАК
,COUNT(ASD.CONTRACT_ID) AS FP_COUNT_FACT --Факт выдач штуки
FROM _DOMAINN_._TABLE1_ AS ASD
LEFT JOIN _DOMAINN_._TABLE3_ AS CIOD
ON		ASD.INIT_INTERNAL_ORG_ID = CIOD.INTERNAL_ORG_ID
AND	CIOD.IS_ACTIVE_FLG = '1'
LEFT JOIN _DOMAIN_.SPR_REG_2016 AS SPR
ON		CIOD.REGIONAL_OFFICE_GEOGRAPHY_NM = SPR.REGIONAL_OFFICE_GEOGRAPHY_NM
WHERE 1=1
AND ASD.ISSUE_DT BETWEEN SELECT_DATE_FACT.DATE_FROM AND SELECT_DATE_FACT.DATE_TO --Период факта выдач должен = периоду плана
AND ASD.PRODUCT_OPERATIONAL_ID IN ('АС','АЛ','АЭ','АП','А1','А2','А5','АУ','АО') --Без АБ
AND ASD.OWNER_TYPE_CD = 'Новый'
AND ASD.BRAND_NM || ASD.MODEL_NM LIKE ANY ('Hyundai%','Jaguar%','Kia%','Lada%','Land Rover%','Lifan%','Subaru%','Suzuki%','UAZ%','Volvo%','ГАЗ%','ChevroletNiva%') --Список марок ФП
GROUP BY MAC
) AS FFP
ON MAK = FFP.MAC

--План неФП штуки
LEFT JOIN
(
SELECT BP_MAK, neFP_COUNT_PLAN_LJ FROM 
	(
	SELECT
	BPTv.MAC AS BP_MAK
	,SUM(VALUE_AMT) AS PLAN_COUNT_NEW --Период плана
	,PFP.FP_PLAN_COUNT AS FP_COUNT_PLAN
	,PLAN_COUNT_NEW - FP_COUNT_PLAN AS neFP_COUNT_PLAN_LJ
	FROM _DOMAIN_.pt_BusinessPlanTotal_vanilla AS BPTv 
	LEFT JOIN
		(
			SELECT 
			BPFv.MAC AS FP_MAK
			,SUM(VALUE_CNT) AS FP_PLAN_COUNT
			FROM _DOMAIN_.pt_BusinessPlanFP_vanilla AS BPFv
			WHERE 1=1
			AND DATE_SYS BETWEEN SELECT_DATE_PLAN.DATE_FROM AND SELECT_DATE_PLAN.DATE_TO --Период плана
			GROUP BY MAC
		) AS PFP --План ФП
	ON BP_MAK = PFP.FP_MAK
	WHERE 1=1
	AND METRIC_NAME = 'выдачи,шт.'
	AND PRODUCT_CODE IN ('1111','1112','1113','1120') --Только новые авто АС 1111	АЭ 1112	АЛ 1113	Balloon 1120
	AND DATE_SYS BETWEEN SELECT_DATE_PLAN.DATE_FROM AND SELECT_DATE_PLAN.DATE_TO --Период плана
	GROUP BY BP_MAK, FP_COUNT_PLAN
	) AS PneFP_FULL
) AS PneFP_SHORT
ON MAK = PneFP_SHORT.BP_MAK

--Факт неФП штуки
LEFT JOIN
(
SELECT
CASE WHEN CIOD.extra_office_id IN ('0019', '0119', '0219', '1019', '1219', '1119', '1319', '1419', '1519', '1719') THEN 'Тольятти' 
	WHEN CIOD.extra_office_id IN ('1015', '1815', '2915', '1115') THEN 'Тюмень' 
	WHEN CIOD.extra_office_id IN ('4215', '2315', '1415', '3015', '2715') THEN 'Сургут' 
ELSE SPR.mak_nm END AS MAC -- Города МАК
,COUNT(ASD.CONTRACT_ID) AS neFP_COUNT_FACT --Факт выдач штуки
FROM _DOMAINN_._TABLE1_ AS ASD
LEFT JOIN _DOMAINN_._TABLE3_ AS CIOD
ON		ASD.INIT_INTERNAL_ORG_ID = CIOD.INTERNAL_ORG_ID
AND	CIOD.IS_ACTIVE_FLG = '1'
LEFT JOIN _DOMAIN_.SPR_REG_2016 AS SPR
ON		CIOD.REGIONAL_OFFICE_GEOGRAPHY_NM = SPR.REGIONAL_OFFICE_GEOGRAPHY_NM
WHERE 1=1
AND ASD.ISSUE_DT BETWEEN SELECT_DATE_FACT.DATE_FROM AND SELECT_DATE_FACT.DATE_TO --Период факта выдач должен = периоду плана
AND ASD.PRODUCT_OPERATIONAL_ID IN ('АС','АЛ','АЭ','АП','А1','А2','А5','АУ','АО') --Без АБ
AND ASD.OWNER_TYPE_CD = 'Новый'
AND ASD.BRAND_NM <> 'Hyundai'
AND ASD.BRAND_NM <> 'Jaguar'
AND ASD.BRAND_NM <> 'Kia'
AND ASD.BRAND_NM <> 'Lada'
AND ASD.BRAND_NM <> 'Land Rover'
AND ASD.BRAND_NM <> 'Lifan'
AND ASD.BRAND_NM <> 'Subaru'
AND ASD.BRAND_NM <> 'Suzuki'
AND ASD.BRAND_NM <> 'UAZ'
AND ASD.BRAND_NM <> 'Volvo'
AND ASD.BRAND_NM <> 'ГАЗ'
AND ASD.BRAND_NM || ASD.MODEL_NM <> 'ChevroletNiva'
GROUP BY MAC
) AS FneFP
ON MAK = FneFP.MAC

--План АСП_дилеры в штуках
LEFT JOIN 
(
SELECT 
MAC
,SUM(VALUE_AMT) AS PLAN_COUNT --Период плана
FROM _DOMAIN_.pt_BusinessPlanTotal_vanilla
WHERE 1=1
AND METRIC_NAME = 'выдачи,шт.'
AND PRODUCT_CODE IN ('1166') --Только АСП БУ 1166
AND DATE_SYS BETWEEN SELECT_DATE_PLAN.DATE_FROM AND SELECT_DATE_PLAN.DATE_TO --Период плана
GROUP BY MAC
) AS ASP_DP
ON MAK = ASP_DP.MAC

--Факт АСП_дилеры в штуках
LEFT JOIN
(
SELECT
CASE WHEN CIOD.extra_office_id IN ('0019', '0119', '0219', '1019', '1219', '1119', '1319', '1419', '1519', '1719') THEN 'Тольятти' 
	WHEN CIOD.extra_office_id IN ('1015', '1815', '2915', '1115') THEN 'Тюмень' 
	WHEN CIOD.extra_office_id IN ('4215', '2315', '1415', '3015', '2715') THEN 'Сургут' 
ELSE SPR.mak_nm END AS MAC -- Города МАК
,COUNT(ASD.CONTRACT_ID) AS ASP_DEALERS_COUNT_FACT --Факт выдач штуки
FROM _DOMAINN_._TABLE1_ AS ASD
LEFT JOIN _DOMAINN_._TABLE3_ AS CIOD
ON		ASD.INIT_INTERNAL_ORG_ID = CIOD.INTERNAL_ORG_ID
AND	CIOD.IS_ACTIVE_FLG = '1'
LEFT JOIN _DOMAIN_.SPR_REG_2016 AS SPR
ON		CIOD.REGIONAL_OFFICE_GEOGRAPHY_NM = SPR.REGIONAL_OFFICE_GEOGRAPHY_NM
LEFT JOIN _DOMAIN3_.PRODUCT_SUB_HIST AS PSH
ON		1=1
AND	ASD.PRODUCT_SUB_ID = PSH.PRODUCT_SUB_ID
AND	PSH.IS_ACTIVE_FLG = '1'
AND	PSH.DELETED_FLG = '0'
WHERE 1=1
AND ASD.ISSUE_DT BETWEEN SELECT_DATE_FACT.DATE_FROM AND SELECT_DATE_FACT.DATE_TO --Период факта выдач должен = периоду плана
AND ASD.PRODUCT_OPERATIONAL_ID IN ('АС','АЛ','АЭ','АП','А1','А2','А5','АУ','АО') --Без АБ
AND UPPER(PSH.PRODUCT_SUB_NM) NOT LIKE '%ФИЗ%'
AND ASD.OWNER_TYPE_CD = 'Старый'
GROUP BY MAC
) AS ASP_DF
ON MAK = ASP_DF.MAC

--План C2C в штуках
LEFT JOIN 
(
SELECT 
MAC
,0 AS PLAN_COUNT --Период плана
FROM _DOMAIN_.pt_BusinessPlanTotal_vanilla
WHERE 1=1
--AND METRIC_NAME = 'выдачи,шт.'
--AND PRODUCT_CODE IN ('1166') --Только АСП БУ 1166
AND DATE_SYS BETWEEN SELECT_DATE_PLAN.DATE_FROM AND SELECT_DATE_PLAN.DATE_TO --Период плана
GROUP BY MAC
) AS PLAN_C2C
ON MAK = PLAN_C2C.MAC

--Факт C2C в штуках
LEFT JOIN
(
SELECT
CASE WHEN CIOD.extra_office_id IN ('0019', '0119', '0219', '1019', '1219', '1119', '1319', '1419', '1519', '1719') THEN 'Тольятти' 
	WHEN CIOD.extra_office_id IN ('1015', '1815', '2915', '1115') THEN 'Тюмень' 
	WHEN CIOD.extra_office_id IN ('4215', '2315', '1415', '3015', '2715') THEN 'Сургут' 
ELSE SPR.mak_nm END AS MAC -- Города МАК
,COUNT(ASD.CONTRACT_ID) AS C2C_COUNT_FACT --Факт выдач штуки
FROM _DOMAINN_._TABLE1_ AS ASD
LEFT JOIN _DOMAINN_._TABLE3_ AS CIOD
ON		ASD.INIT_INTERNAL_ORG_ID = CIOD.INTERNAL_ORG_ID
AND	CIOD.IS_ACTIVE_FLG = '1'
LEFT JOIN _DOMAIN_.SPR_REG_2016 AS SPR
ON		CIOD.REGIONAL_OFFICE_GEOGRAPHY_NM = SPR.REGIONAL_OFFICE_GEOGRAPHY_NM
LEFT JOIN _DOMAIN3_.PRODUCT_SUB_HIST AS PSH
ON		1=1
AND	ASD.PRODUCT_SUB_ID = PSH.PRODUCT_SUB_ID
AND	PSH.IS_ACTIVE_FLG = '1'
AND	PSH.DELETED_FLG = '0'
WHERE 1=1
AND ASD.ISSUE_DT BETWEEN SELECT_DATE_FACT.DATE_FROM AND SELECT_DATE_FACT.DATE_TO --Период факта выдач должен = периоду плана
AND ASD.PRODUCT_OPERATIONAL_ID IN ('АС','АЛ','АЭ','АП','А1','А2','А5','АУ','АО') --Без АБ
AND UPPER(PSH.PRODUCT_SUB_NM) LIKE '%ФИЗ%'
AND ASD.OWNER_TYPE_CD = 'Старый'
GROUP BY MAC
) AS FACT_C2C
ON MAK = FACT_C2C.MAC

--План АБ в штуках
LEFT JOIN 
(
SELECT 
MAC
,SUM(VALUE_AMT) AS PLAN_COUNT --Период плана
FROM _DOMAIN_.pt_BusinessPlanTotal_vanilla
WHERE 1=1
AND METRIC_NAME = 'выдачи,шт.'
AND PRODUCT_CODE IN ('1119') --Только АБ 1119
AND DATE_SYS BETWEEN SELECT_DATE_PLAN.DATE_FROM AND SELECT_DATE_PLAN.DATE_TO --Период плана
GROUP BY MAC
) AS PLAN_AB
ON MAK = PLAN_AB.MAC

--Факт АБ в штуках
LEFT JOIN
(
SELECT
CASE WHEN CIOD.extra_office_id IN ('0019', '0119', '0219', '1019', '1219', '1119', '1319', '1419', '1519', '1719') THEN 'Тольятти' 
	WHEN CIOD.extra_office_id IN ('1015', '1815', '2915', '1115') THEN 'Тюмень' 
	WHEN CIOD.extra_office_id IN ('4215', '2315', '1415', '3015', '2715') THEN 'Сургут' 
ELSE SPR.mak_nm END AS MAC -- Города МАК
,COUNT(ASD.CONTRACT_ID) AS AB_COUNT_FACT --Факт выдач АБ штуки
FROM _DOMAINN_._TABLE1_ AS ASD
LEFT JOIN _DOMAINN_._TABLE3_ AS CIOD
ON		ASD.INIT_INTERNAL_ORG_ID = CIOD.INTERNAL_ORG_ID
AND	CIOD.IS_ACTIVE_FLG = '1'
LEFT JOIN _DOMAIN_.SPR_REG_2016 AS SPR
ON		CIOD.REGIONAL_OFFICE_GEOGRAPHY_NM = SPR.REGIONAL_OFFICE_GEOGRAPHY_NM
LEFT JOIN _DOMAIN3_.PRODUCT_SUB_HIST AS PSH
ON		1=1
AND	ASD.PRODUCT_SUB_ID = PSH.PRODUCT_SUB_ID
AND	PSH.IS_ACTIVE_FLG = '1'
AND	PSH.DELETED_FLG = '0'
WHERE 1=1
AND ASD.ISSUE_DT BETWEEN SELECT_DATE_FACT.DATE_FROM AND SELECT_DATE_FACT.DATE_TO --Период факта выдач должен = периоду плана
AND ASD.PRODUCT_OPERATIONAL_ID IN ('АБ') --Только АБ
GROUP BY MAC
) AS FACT_AB
ON MAK = FACT_AB.MAC

--Проникновение СУ
LEFT JOIN _DOMAIN_.pt_SU_PENETRATION AS SUP
ON MAK = SUP.MAC

--Средний вес
LEFT JOIN _DOMAIN_.pt_SRED_VES AS SV
ON MAK = SV.MAC

WHERE 1=1
AND ASD.ISSUE_DT BETWEEN SELECT_DATE_FACT.DATE_FROM AND SELECT_DATE_FACT.DATE_TO --Период факта выдач должен = периоду плана
AND ASD.PRODUCT_OPERATIONAL_ID IN ('АС','АЛ','АЭ','АБ','АП','А1','А2','А5','АУ','АО')
GROUP BY DATE_FROM, DATE_TO, MAK, TOTAL_COUNT_PLAN, TOTAL_SUM_PLAN, FP_COUNT_PLAN, FP_COUNT_FACT, neFP_COUNT_PLAN, neFP_COUNT_FACT,
ASP_D_COUNT_FACT, ASP_D_COUNT_PLAN, C2C_COUNT_PLAN, C2C_COUNT_FACT, VKASKO_PENET_SHT, VKASKO_PENET_RUB, MKASKO_PENET_SHT, MKASKO_PENET_RUB,
SJ_PENET_SHT, SJ_PENET_RUB, DKASKO_PENET_SHT, DKASKO_PENET_RUB, RAMK_PENET_SHT, RAMK_PENET_RUB, AVL_PENET_SHT, AVL_PENET_RUB, SV_STAVKAGP, SV_SROKKRED,
AB_COUNT_PLAN, AB_COUNT_FACT, SV_PV, SV_VEH_COST


