SELECT DISTINCT
ASD.CONTRACT_ID AS DOGOVOR -- Номер кредитного договора	
,ASD.ISSUE_DT AS DTV -- Дата выдачи
,CASE	WHEN EXTRACT(MONTH FROM ASD.issue_dt) <10 THEN TRIM ( LEADING ' ' FROM EXTRACT(YEAR FROM ASD.issue_dt)) || '_0' || TRIM (LEADING ' ' FROM EXTRACT(MONTH FROM ASD.issue_dt))
			ELSE  TRIM ( LEADING ' ' FROM EXTRACT(YEAR FROM ASD.issue_dt)) || '_' || TRIM (LEADING ' ' FROM EXTRACT(MONTH FROM ASD.issue_dt)) 
END AS DTYM -- Поколение выдачи
,CASE WHEN ASD.PRODUCT_OPERATIONAL_ID IN  ('А1','А2','А5') THEN 'АЭ' ELSE ASD.PRODUCT_OPERATIONAL_ID END PRODUCT --	Продукт
,CASE
			WHEN (UPPER(PSH.product_sub_nm) LIKE '%LIFAN FINANCE%' AND ASD.product_operational_id = 'АЛ') THEN 'Lifan (6.9%)'
			WHEN (UPPER(PSH.product_sub_nm) LIKE '%FORCE%' AND ASD.product_operational_id = 'АЛ') THEN 'Lifan (7.34%)'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%KICK DOWN LOCAL%' THEN 'Kick down local'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%KICK DOWN PLUS%' THEN 'Kick down Plus'
			WHEN (UPPER(PSH.product_sub_nm) LIKE '%KICK%' AND ASD.product_operational_id NOT IN ('АБ')) THEN 'Kick down' /*AND X.BRAND_NM NOT IN ('Ford'*/
			/*WHEN (upper(PSH.product_sub_nm) LIKE '%KICK%' AND ASD.product_operational_id NOT IN ('АБ') AND ASD.BRAND_NM = 'Ford') THEN 'Ford Kick down'*/
			WHEN UPPER(PSH.product_sub_nm) LIKE '%Ъ%' THEN 'ЭкспрессЪ'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%МИЛЛИОН%' THEN 'Миллион'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%ПРИВИЛЕГИЯ%' THEN 'АвтоПривилегия'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%FINANCIAL SERVICES DIRECT%' THEN 'ПРС Land_Jaguar'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%VOLVO DIRECT%' THEN 'ПРС Volvo'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%ДРАЙВЕР%' THEN 'Драйвер'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%АВТОКОРПОРАЦИЯ%' THEN 'АвтоКорпорация'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%ФИЗ%' THEN 'C2C'
			WHEN (UPPER(PSH.product_sub_nm) LIKE '%LADA FINANCE SPECIAL%' AND PSH.product_sub_nm LIKE '%02.11.2016%' AND ASD.brand_nm IN ('Lada') AND ASD.product_operational_id NOT IN ('АБ')) THEN 'Lada Finance Special'
            WHEN (UPPER(PSH.product_sub_nm) LIKE '%LADA FINANCE SPECIAL%' AND PSH.product_sub_nm LIKE '%02.02.2017%' AND ASD.brand_nm IN ('Lada') AND ASD.product_operational_id NOT IN ('АБ')) THEN 'Lada Finance Special'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%С ПОНИЖАЮЩИМ!%' THEN 'С понижающим!'
			WHEN UPPER(PSH.product_sub_nm) LIKE '%BLACKAUTOFRIDAY%' THEN 'BlackAutoFriday'
			WHEN UPPER(ASD.PRODUCT_SUB_NM) LIKE '%ДАЙ ПЯТЬ!%' THEN 'Дай пять!'
			WHEN UPPER(PSH.PRODUCT_SUB_NM) LIKE '%АВТОЛАЙТ ПРОМО%'  AND ASD.OWNER_TYPE_CD = 'Старый' THEN 'Автопробег'
			ELSE 'Прочее'
END AS PROGRAMMA -- Раскраска Программы
,CASE 
	WHEN CIOD.extra_office_id IN ('0019', '0119', '0219', '1019', '1219', '1119', '1319', '1419', '1519', '1719') THEN 'Тольятти' 
	WHEN CIOD.extra_office_id IN ('1015', '1815', '2915', '1115') THEN 'Тюмень' 
	WHEN CIOD.extra_office_id IN ('4215', '2315', '1415', '3015', '2715') THEN 'Сургут'
	WHEN CIOD.extra_office_id IN ('2464') THEN 'Уфа'	
ELSE SPR.mak_nm 
END AS MAK -- Города МАК
,ASD.OWNER_TYPE_CD AS New_Old -- Новый а/м или АСП
,ASD.LOAN_RUR_AMT --- Сумма выдачи в рублях
,ASD.AUTO_HOLDING_LVL_1_CD AS HOLDING
,CASE WHEN ASD.brand_nm = 'Chevrolet' AND ASD.model_nm = 'Niva' THEN 'Chevrolet Niva' ELSE ASD.brand_nm END AS Marka
,CASE 
	 WHEN Marka = 'Chevrolet Niva' THEN 'ФП'
	 WHEN Marka = 'Hyundai' THEN 'ФП'
	 WHEN Marka = 'Jaguar' THEN 'ФП'
	 WHEN Marka = 'Kia' THEN 'ФП'
	 WHEN Marka = 'Lada' THEN 'ФП'
	 WHEN Marka = 'Land Rover' THEN 'ФП'
	 WHEN Marka = 'Lifan' THEN 'ФП'
	 WHEN Marka = 'Subaru' THEN 'ФП'
	 WHEN Marka = 'Suzuki' THEN 'ФП'
	 WHEN Marka = 'UAZ' THEN 'ФП'
	 WHEN Marka = 'Volvo' THEN 'ФП'
	 WHEN Marka = 'ГАЗ' THEN 'ФП'
	 ELSE 'неФП'
END AS FP_notFP -- Марка а/м ФП или неФП
,CASE 
	WHEN DV.vehicle_manufacturer_residence = 'RUS' THEN 'Отечественная'
	WHEN DV.vehicle_manufacturer_residence = 'NORUS' THEN 'Иномарка'
	ELSE 'Нет информации' 
END AS RUS_NO
-----SU sector
,1 AS KRED -- Кредиты счетчик
,CASE 
	WHEN ASD.COMPREH_COVER_INSURANT_NM LIKE '%ВТБ%' AND ASD.COMPREH_COVER_CONTRACT_ID LIKE '%А342%' THEN 1 --кириллица
	WHEN ASD.COMPREH_COVER_INSURANT_NM LIKE '%ВТБ%' AND ASD.COMPREH_COVER_CONTRACT_ID LIKE '%A342%' THEN 1 --латиница
	ELSE 0 
END AS VKASKO_VTB -- ВместоКаско ВТБ-С
,CASE 
	WHEN ASD.COMPREH_COVER_INSURANT_NM LIKE '%ВТБ%' AND ASD.COMPREH_COVER_CONTRACT_ID LIKE '%A302%' THEN 1 --латиница
	WHEN ASD.COMPREH_COVER_INSURANT_NM LIKE '%ВТБ%' AND ASD.COMPREH_COVER_CONTRACT_ID LIKE '%А302%' THEN 1 --кириллица
	WHEN ASD.COMPREH_COVER_INSURANT_NM LIKE '%ВТБ%' AND ASD.COMPREH_COVER_CONTRACT_ID LIKE '%A301%' THEN 1 --латиница
	WHEN ASD.COMPREH_COVER_INSURANT_NM LIKE '%ВТБ%' AND ASD.COMPREH_COVER_CONTRACT_ID LIKE '%А301%' THEN 1 --кириллица
	ELSE 0 
END AS MINIK -- МиниКАСКО ВТБ-С
,CASE WHEN ASD.life_insurance_insurant_nm IS NOT NULL THEN
	CASE WHEN UPPER (ASD.life_insurance_contract_id) LIKE '%K%' 
		OR UPPER (ASD.life_insurance_contract_id) LIKE '%К%'
		OR UPPER (ASD.life_insurance_contract_id) LIKE '%A%'
		OR UPPER (ASD.life_insurance_contract_id) LIKE '%А%'
		OR UPPER (ASD.life_insurance_insurant_nm) LIKE '%ВТБ%' THEN 1 ELSE 0 
	END ELSE 0 
END AS SJVTB -- СЖ ВТБ
,CASE
	WHEN UPPER (AIHDK2.INSURANCE_COMPANY_ID) LIKE '%ВТБ%' THEN 1	--new logic
	WHEN UPPER (AIHDK2.INSURANCE_CONTRACT_ID) LIKE '%K%' THEN 1		--new logic	
	WHEN UPPER (AIHDK2.INSURANCE_CONTRACT_ID) LIKE '%К%' THEN 1		--new logic
	WHEN UPPER (AIHDK2.INSURANCE_CONTRACT_ID) LIKE '%A%' THEN 1		--new logic
	WHEN UPPER (AIHDK2.INSURANCE_CONTRACT_ID) LIKE '%А%' THEN 1		--new logic
	ELSE 0 
END AS DKVTB  -------ДКАСКО ВТБ 
------Rastorjenia SU VTB
,CASE WHEN CPVK.CONTRACT_ID IS NOT NULL THEN 1 ELSE 0 END AS FLG_VK_RASTOR
,CASE WHEN CPMK.CONTRACT_ID IS NOT NULL THEN 1 ELSE 0 END AS FLG_MK_RASTOR
,CASE WHEN CPSJ.CONTRACT_ID IS NOT NULL THEN 1 ELSE 0 END AS FLG_SJ_RASTOR
,CASE WHEN CPDK.CONTRACT_ID IS NOT NULL THEN 1 ELSE 0 END AS FLG_DK_RASTOR
----Premii
,CASE WHEN ASD.COMPREH_COVER_INSURANT_NM LIKE '%ВТБ%' THEN ASD.COMPREH_COVER_PAYMENT_AMT ELSE NULL 
END AS Страх_премия_ВместоКАСКО_ВТБ
,CASE WHEN ASD.COMPREH_COVER_INSURANT_NM LIKE '%ВТБ%' AND ASD.COMPREH_COVER_PAYMENT_DESC LIKE '%за счет%' THEN ASD.COMPREH_COVER_PAYMENT_AMT ELSE NULL 
END AS Страх_премия_МиниКАСКО_ВТБ
,CASE WHEN ASD.LIFE_INSURANCE_INSURANT_NM LIKE '%ВТБ%' THEN ASD.LIFE_INSURANCE_PAYMENT_AMT ELSE NULL 
END AS Страх_премия_СЖ_ВТБ
,CASE 
	WHEN UPPER (AIHDK2.INSURANCE_COMPANY_ID) LIKE '%ВТБ%' THEN CAST(RIHDK2.PAYMENT_AMT AS DECIMAL(23,2))
	WHEN UPPER (AIHDK2.INSURANCE_CONTRACT_ID) LIKE '%K%' THEN CAST(RIHDK2.PAYMENT_AMT AS DECIMAL(23,2))
	WHEN UPPER (AIHDK2.INSURANCE_CONTRACT_ID) LIKE '%К%' THEN CAST(RIHDK2.PAYMENT_AMT AS DECIMAL(23,2))
	WHEN UPPER (AIHDK2.INSURANCE_CONTRACT_ID) LIKE '%A%' THEN CAST(RIHDK2.PAYMENT_AMT AS DECIMAL(23,2))
	WHEN UPPER (AIHDK2.INSURANCE_CONTRACT_ID) LIKE '%А%' THEN CAST(RIHDK2.PAYMENT_AMT AS DECIMAL(23,2))
	ELSE NULL
END AS Страх_премия_ДКАСКО_ВТБ
--------------------------
,CASE 
	WHEN PROGRAMMA = 'C2C' THEN 1
	WHEN MAK = 'Москва' AND UPPER(HOLDING) = 'Х_СИМ' THEN 1
	WHEN MAK = 'Москва' AND UPPER(HOLDING) = 'Х_АВАЛЮКС' THEN 1
	WHEN MAK = 'Москва' AND UPPER(HOLDING) = 'Х_ЯХРОМА' THEN 1
	WHEN MAK = 'Москва' AND UPPER(HOLDING) = 'Х_АВТОГАЗ' THEN 1
	WHEN MAK = 'Москва' AND UPPER(HOLDING) = 'Х_РТР_АВТО' THEN 1
	WHEN MAK = 'Москва' AND UPPER(HOLDING) = 'Х_ГК_БЛОК' THEN 1
	WHEN MAK = 'Москва' AND UPPER(HOLDING) = 'Х_АВИНЬОН' THEN 1
	WHEN MAK = 'Москва' AND UPPER(HOLDING) = 'Х_ОРЕХОВО_АВТО_ЦЕНТР' THEN 1
	WHEN MAK = 'Москва' AND UPPER(HOLDING) = 'Х_ВИСТ_АВТО' THEN 1
	WHEN MAK = 'Самара' AND UPPER(HOLDING) = 'Х_АСАВТО' THEN 1
	WHEN MAK = 'Самара' AND UPPER(HOLDING) = 'Х_АСАВТО-ТОЛЬЯТТИ' THEN 1
	WHEN MAK = 'Самара' AND UPPER(HOLDING) = 'Х_АВТОСАЛОН_АСАВТО' THEN 1
	WHEN MAK = 'Самара' AND UPPER(HOLDING) = 'Х_АВТО-БРОКЕР' THEN 1
	WHEN MAK = 'Самара' AND UPPER(HOLDING) = 'Х_АВТОСАЛОН_АРГО' THEN 1
	WHEN MAK = 'Санкт-Петербург' AND UPPER(HOLDING) = 'Х_АКСЕЛЬ' THEN 1
	WHEN MAK = 'Санкт-Петербург' AND UPPER(HOLDING) = 'Х_АВРОРА' THEN 1
	WHEN MAK = 'Санкт-Петербург' AND UPPER(HOLDING) = 'X_АВТОПРОДИКС' THEN 1
	WHEN MAK = 'Санкт-Петербург' AND UPPER(HOLDING) = 'X_МОНКОМ' THEN 1
	WHEN MAK = 'Калининград' AND UPPER(HOLDING) = 'Х_ДИНАМИКА_КАЛИНИНГР' THEN 1
	WHEN MAK = 'Калининград' AND UPPER(HOLDING) = 'Х_ДО-КАР' THEN 1
	WHEN MAK = 'Екатеринбург' AND UPPER(HOLDING) = 'Х_АСМОТО' THEN 1
	WHEN MAK = 'Екатеринбург' AND UPPER(HOLDING) = 'Х_АВТОЛИДЕР' THEN 1
	WHEN MAK = 'Екатеринбург' AND UPPER(HOLDING) = 'Х_БЕРЕЗОВСКИЙ_ПРИВОЗ' THEN 1
	WHEN MAK = 'Екатеринбург' AND UPPER(HOLDING) = 'Х_АМК_ЕКАТЕРИНБУРГ' THEN 1
	WHEN MAK = 'Екатеринбург' AND UPPER(HOLDING) = 'Х_ТРАНССЕРВИС' THEN 1
	WHEN MAK = 'Екатеринбург' AND UPPER(HOLDING) = 'Х_ОК_ТРАНС' THEN 1
	WHEN MAK = 'Тюмень' AND UPPER(HOLDING) = 'Х_АВТОГРАД-ТЮМЕНЬ' THEN 1
	WHEN MAK = 'Тюмень' AND UPPER(HOLDING) = 'Х_НИККО' THEN 1
	WHEN MAK = 'Пенза' AND UPPER(HOLDING) = 'Х_СУРА_МОТОРС' THEN 1
	WHEN MAK = 'Пенза' AND UPPER(HOLDING) = 'Х_СУРА_МОТОРС_АВТО' THEN 1
	WHEN MAK = 'Пенза' AND UPPER(HOLDING) = 'Х_АВТОЛОЦМАН' THEN 1
	WHEN MAK = 'Воронеж' AND UPPER(HOLDING) = 'Х_РИНГ_ВОРОНЕЖ' THEN 1
	WHEN MAK = 'Воронеж' AND UPPER(HOLDING) = 'Х_БОР_АВТО' THEN 1
	WHEN MAK = 'Воронеж' AND UPPER(HOLDING) = 'Х_СОКРАТ' THEN 1
	WHEN MAK = 'Белгород' AND UPPER(HOLDING) = 'Х_ДЖЕНСЕР' THEN 1
	WHEN MAK = 'Ижевск' AND UPPER(HOLDING) = 'Х_ФОРВАРД_АВТО' THEN 1
	ELSE 0
END AS MKASKO_znam_flag

FROM CDM_YPDN_NCDN_N72.FCT_AUTO_SALE_DAILY AS ASD

LEFT JOIN	CDM_YPDN_NCDN_N72.cd_internal_org_detail AS CIOD
ON		ASD.init_internal_org_id = CIOD.internal_org_id
AND	CIOD.is_active_flg = '1'

LEFT JOIN	PROD_DAB_URSP_OAPP_SBX.spr_reg_2016 AS SPR
ON		CIOD.regional_office_geography_nm = SPR.regional_office_geography_nm

LEFT JOIN	PROD_DAB_URSP_OAPP_SBX.spr_GAK_2016 AS sprgak
ON 		1=1
AND	CIOD.extra_office_id = sprgak.extra_office_id

LEFT JOIN DDS_YPDN_NCDN_N72.PRODUCT_SUB_HIST AS PSH
ON		1=1
AND	ASD.PRODUCT_SUB_ID = PSH.PRODUCT_SUB_ID
AND	PSH.IS_ACTIVE_FLG = '1'
AND	PSH.DELETED_FLG = '0'

LEFT JOIN	DDS_YPDN_NCDN_N72.dim_vehicle AS DV
ON 	1=1
AND	DV.vehicle_cd = UPPER(ASD.brand_nm)
AND	DV.parent_vehicle_cd = 'ПК-МАРКИМОДЕЛИ'

LEFT JOIN	PROD_DAB_URSP_OAPP_SBX.COOLING_PERIOD AS CPSJ
ON	1=1
AND	CPSJ.CONTRACT_ID = ASD.CONTRACT_ID
AND	CPSJ.INSUR_TYPE = 'СЖ'
AND	CPSJ.INSUR_NM = 'ВТБ-С'

LEFT JOIN	PROD_DAB_URSP_OAPP_SBX.COOLING_PERIOD AS CPDK
ON	1=1
AND	CPDK.CONTRACT_ID = ASD.CONTRACT_ID
AND	CPDK.INSUR_TYPE = 'ДКАСКО'
AND	CPDK.INSUR_NM = 'ВТБ-С'

LEFT JOIN	PROD_DAB_URSP_OAPP_SBX.COOLING_PERIOD AS CPVK
ON	1=1
AND	CPVK.CONTRACT_ID = ASD.CONTRACT_ID
AND	CPVK.INSUR_TYPE = 'ВместоКАСКО'
AND	CPVK.INSUR_NM = 'ВТБ-С'

LEFT JOIN	PROD_DAB_URSP_OAPP_SBX.COOLING_PERIOD AS CPMK
ON	1=1
AND	CPMK.CONTRACT_ID = ASD.CONTRACT_ID
AND	CPMK.INSUR_TYPE = 'МиниКАСКО'
AND	CPMK.INSUR_NM = 'ВТБ-С'

LEFT JOIN 
(
SELECT * FROM DDS_YPDN_NCDN_N72.AGREEMENT_INSURANCE_HIST AS AIHRAMK
WHERE 1=1
AND	AIHRAMK.EFFECTIVE_TO_DTTM = '5999-12-31 00:00:00'
AND	AIHRAMK.DELETED_FLG = '0'
AND	AIHRAMK.IS_ACTIVE_FLG = '1'
AND	AIHRAMK.EXECUTE_FLG = '1'
AND	AIHRAMK.PARENT_AGREEMENT_TYPE_CD = 'КРЕДИТ'
AND	AIHRAMK.SOURCE_SYSTEM_CD IN ('00040', '00000', '00002', '00056', '00055', '00051', '00018', '00006', '00060')
AND   AIHRAMK.INSURANCE_RISK_TYPE_CD IN ('31', '7') --РАМК
QUALIFY	ROW_NUMBER() OVER (PARTITION BY AIHRAMK.PARENT_AGREEMENT_RK ORDER BY AIHRAMK.EFFECTIVE_FROM_DTTM DESC) = 1	 
) AS AIHRAMK2
ON	AIHRAMK2.PARENT_AGREEMENT_RK = ASD.AGREEMENT_RK

LEFT JOIN 
(
SELECT * FROM DDS_YPDN_NCDN_N72.REPAYMENT_INSURANCE_HIST AS RIHRAMK
WHERE 1=1
AND	RIHRAMK.EFFECTIVE_TO_DTTM = '5999-12-31 00:00:00'
AND	RIHRAMK.DELETED_FLG = '0'
AND	RIHRAMK.IS_ACTIVE_FLG = '1'
AND	RIHRAMK.PAYMENT_FLG = 'ДА'
AND	RIHRAMK.PARENT_AGREEMENT_TYPE_CD = 'КРЕДИТ'
AND	RIHRAMK.SOURCE_SYSTEM_CD IN ('00040', '00000', '00002', '00056', '00055', '00051', '00018', '00006', '00060')
AND   RIHRAMK.INSURANCE_RISK_TYPE_CD IN ('31', '7') --РАМК
QUALIFY	ROW_NUMBER() OVER (PARTITION BY RIHRAMK.PARENT_AGREEMENT_RK ORDER BY RIHRAMK.EFFECTIVE_FROM_DTTM DESC) = 1
) AS RIHRAMK2
ON	RIHRAMK2.PARENT_AGREEMENT_RK = ASD.AGREEMENT_RK

LEFT JOIN 
(
SELECT * FROM DDS_YPDN_NCDN_N72.AGREEMENT_INSURANCE_HIST AS AIHAVL
WHERE 1=1
AND	AIHAVL.EFFECTIVE_TO_DTTM = '5999-12-31 00:00:00'
AND	AIHAVL.DELETED_FLG = '0'
AND	AIHAVL.IS_ACTIVE_FLG = '1'
AND	AIHAVL.EXECUTE_FLG = '1'
AND	AIHAVL.PARENT_AGREEMENT_TYPE_CD = 'КРЕДИТ'
AND	AIHAVL.SOURCE_SYSTEM_CD IN ('00040', '00000', '00002', '00056', '00055', '00051', '00018', '00006', '00060')
AND   AIHAVL.INSURANCE_RISK_TYPE_CD IN ('33', '7') --Автолюбитель
QUALIFY	ROW_NUMBER() OVER (PARTITION BY AIHAVL.PARENT_AGREEMENT_RK ORDER BY AIHAVL.EFFECTIVE_FROM_DTTM DESC) = 1
) AS AIHAVL2
ON	AIHAVL2.PARENT_AGREEMENT_RK = ASD.AGREEMENT_RK

LEFT JOIN 
(
SELECT * FROM DDS_YPDN_NCDN_N72.REPAYMENT_INSURANCE_HIST AS RIHAVL
WHERE 1=1
AND	RIHAVL.EFFECTIVE_TO_DTTM = '5999-12-31 00:00:00'
AND	RIHAVL.DELETED_FLG = '0'
AND	RIHAVL.IS_ACTIVE_FLG = '1'
AND	RIHAVL.PAYMENT_FLG = 'ДА'
AND	RIHAVL.PARENT_AGREEMENT_TYPE_CD = 'КРЕДИТ'
AND	RIHAVL.SOURCE_SYSTEM_CD IN ('00040', '00000', '00002', '00056', '00055', '00051', '00018', '00006', '00060')
AND   RIHAVL.INSURANCE_RISK_TYPE_CD IN ('33', '7') --Автолюбитель
QUALIFY	ROW_NUMBER() OVER (PARTITION BY RIHAVL.PARENT_AGREEMENT_RK ORDER BY RIHAVL.EFFECTIVE_FROM_DTTM DESC) = 1
) AS RIHAVL2
ON	RIHAVL2.PARENT_AGREEMENT_RK = ASD.AGREEMENT_RK

LEFT JOIN 
(
SELECT * FROM DDS_YPDN_NCDN_N72.AGREEMENT_INSURANCE_HIST AS AIHDK
WHERE 1=1
AND	AIHDK.EFFECTIVE_TO_DTTM = '5999-12-31 00:00:00'
AND	AIHDK.DELETED_FLG = '0'
AND	AIHDK.IS_ACTIVE_FLG = '1'
AND	AIHDK.EXECUTE_FLG = '1'
AND	AIHDK.PARENT_AGREEMENT_TYPE_CD = 'КРЕДИТ'
AND	AIHDK.SOURCE_SYSTEM_CD IN ('00040', '00000', '00002', '00056', '00055', '00051', '00018', '00006', '00060')
AND   AIHDK.INSURANCE_RISK_TYPE_CD IN ('32', '7') --ДКАСКО
QUALIFY	ROW_NUMBER() OVER (PARTITION BY AIHDK.PARENT_AGREEMENT_RK ORDER BY AIHDK.EFFECTIVE_FROM_DTTM DESC) = 1
) AS AIHDK2
ON	AIHDK2.PARENT_AGREEMENT_RK = ASD.AGREEMENT_RK

LEFT JOIN 
(
SELECT * FROM DDS_YPDN_NCDN_N72.REPAYMENT_INSURANCE_HIST AS RIHDK
WHERE 1=1
AND	RIHDK.EFFECTIVE_TO_DTTM = '5999-12-31 00:00:00'
AND	RIHDK.DELETED_FLG = '0'
AND	RIHDK.IS_ACTIVE_FLG = '1'
AND	RIHDK.PAYMENT_FLG = 'ДА'
AND	RIHDK.PARENT_AGREEMENT_TYPE_CD = 'КРЕДИТ'
AND	RIHDK.SOURCE_SYSTEM_CD IN ('00040', '00000', '00002', '00056', '00055', '00051', '00018', '00006', '00060')
AND   RIHDK.INSURANCE_RISK_TYPE_CD IN ('32', '7') --ДКАСКО
QUALIFY	ROW_NUMBER() OVER (PARTITION BY RIHDK.PARENT_AGREEMENT_RK ORDER BY RIHDK.EFFECTIVE_FROM_DTTM DESC) = 1
) AS RIHDK2
ON	RIHDK2.PARENT_AGREEMENT_RK = ASD.AGREEMENT_RK

LEFT JOIN CDM_YPDN_NCDN_N72.AGG_BP_LOAN_ISSUE AS ABLI
ON ASD.CONTRACT_ID = ABLI.CONTRACT_ID
AND ABLI.PLAN_ALGORITHM_VERSION = '3'
AND ABLI.ISSUE_AMT > 0

WHERE 1=1
AND ASD.ISSUE_DT BETWEEN '2017-10-01' AND (SELECT (DATE-DAY_OF_WEEK(DATE))+0)                --(SELECT (DATE-DAY_OF_WEEK(DATE))+1) --- Меняем Дату на текущую--(LAST SUNDAY)
AND ASD.PRODUCT_OPERATIONAL_ID IN ('АС','АЛ','АЭ','АБ','АП','А1','А2','А5','АУ','АО')





